#ifndef _DIV_BY_S_I_H_
#define _DIV_BY_S_I_H_

#define DIV_S0(mult_factor,offset) do {                                \
        g[offset+0] += g[offset+1] * mult_factor;  \
        g[offset+1] += g[offset+0];                                    \
} while (0)

#define INV_DIV_S0(mult_factor,offset) do {                                \
        g[offset+1] += g[offset+0];                                    \
        g[offset+0] += g[offset+1] * mult_factor;  \
} while (0)


#define DIV_S1(mult_factor,offset) do {                                \
        g[offset+2] += g[offset+3];                               \
        g[offset+1] += (g[offset+3] * mult_factor) + g[offset+2];                                         \
        g[offset+0] += g[offset+2] * mult_factor;                                                          \
        g[offset+2] += g[offset+0]; \
        g[offset+3] += g[offset+1]; \
} while (0)

#define INV_DIV_S1(mult_factor,offset) do {                                \
        g[offset+2] += g[offset+0]; \
        g[offset+3] += g[offset+1]; \
        g[offset+1] += g[offset+3] * mult_factor;                                         \
        g[offset+0] += g[offset+2] * mult_factor;                                                          \
        g[offset+1] += g[offset+2];                               \
        g[offset+2] += g[offset+3];                               \
} while (0)


#define DIV_S2(mult_factor,offset) do {                                \
        g[offset+4] += g[offset+7];                       \
        g[offset+3] += g[offset+6];                       \
        g[offset+2] += g[offset+5];                       \
        g[offset+1] += g[offset+4];                       \
        g[offset+3] += g[offset+7] * mult_factor;  \
        g[offset+2] += g[offset+6] * mult_factor;  \
        g[offset+1] += g[offset+5] * mult_factor;  \
        g[offset+0] += g[offset+4] * mult_factor;  \
        g[offset+4] += g[offset+0];                       \
        g[offset+5] += g[offset+1];                       \
        g[offset+6] += g[offset+2];                       \
        g[offset+7] += g[offset+3];                       \
} while (0)

#define INV_DIV_S2(mult_factor,offset) do {                                \
        g[offset+4] += g[offset+0];                       \
        g[offset+5] += g[offset+1];                       \
        g[offset+6] += g[offset+2];                       \
        g[offset+7] += g[offset+3];                       \
        g[offset+3] += g[offset+7] * mult_factor;  \
        g[offset+2] += g[offset+6] * mult_factor;  \
        g[offset+1] += g[offset+5] * mult_factor;  \
        g[offset+0] += g[offset+4] * mult_factor;  \
        g[offset+1] += g[offset+4];                       \
        g[offset+2] += g[offset+5];                       \
        g[offset+3] += g[offset+6];                       \
        g[offset+4] += g[offset+7];                       \
} while (0)


#define DIV_S3(mult_factor,offset) do {                                \
        g[offset+8]  += g[offset+15];                       \
        g[offset+9]  += g[offset+15];                       \
        g[offset+11] += g[offset+15];                       \
        g[offset+7]  += g[offset+14];                       \
        g[offset+8]  += g[offset+14];                       \
        g[offset+10] += g[offset+14];                       \
        g[offset+6]  += g[offset+13];                       \
        g[offset+7]  += g[offset+13];                       \
        g[offset+9]  += g[offset+13];                       \
        g[offset+5]  += g[offset+12];                       \
        g[offset+6]  += g[offset+12];                       \
        g[offset+8]  += g[offset+12];                       \
        g[offset+4]  += g[offset+11];                       \
        g[offset+5]  += g[offset+11];                       \
        g[offset+7]  += g[offset+11];                       \
        g[offset+3]  += g[offset+10];                       \
        g[offset+4]  += g[offset+10];                       \
        g[offset+6]  += g[offset+10];                       \
        g[offset+2]  += g[offset+9];                       \
        g[offset+3]  += g[offset+9];                       \
        g[offset+5]  += g[offset+9];                       \
        g[offset+1]  += g[offset+8];                       \
        g[offset+2]  += g[offset+8];                       \
        g[offset+4]  += g[offset+8];                       \
        g[offset+7]  += g[offset+15] * mult_factor;  \
        g[offset+6]  += g[offset+14] * mult_factor;  \
        g[offset+5]  += g[offset+13] * mult_factor;  \
        g[offset+4]  += g[offset+12] * mult_factor;  \
        g[offset+3]  += g[offset+11] * mult_factor;  \
        g[offset+2]  += g[offset+10] * mult_factor;  \
        g[offset+1]  += g[offset+9]  * mult_factor;   \
        g[offset+0]  += g[offset+8]  * mult_factor;   \
        g[offset+8]  += g[offset+0];                       \
        g[offset+9]  += g[offset+1];                       \
        g[offset+10] += g[offset+2];                       \
        g[offset+11] += g[offset+3];                       \
        g[offset+12] += g[offset+4];                       \
        g[offset+13] += g[offset+5];                       \
        g[offset+14] += g[offset+6];                       \
        g[offset+15] += g[offset+7];                       \
} while (0)

#define INV_DIV_S3(mult_factor,offset) do {                                \
        g[offset+8]  += g[offset+0];                       \
        g[offset+9]  += g[offset+1];                       \
        g[offset+10] += g[offset+2];                       \
        g[offset+11] += g[offset+3];                       \
        g[offset+12] += g[offset+4];                       \
        g[offset+13] += g[offset+5];                       \
        g[offset+14] += g[offset+6];                       \
        g[offset+15] += g[offset+7];                       \
        g[offset+7]  += g[offset+15] * mult_factor;  \
        g[offset+6]  += g[offset+14] * mult_factor;  \
        g[offset+5]  += g[offset+13] * mult_factor;  \
        g[offset+4]  += g[offset+12] * mult_factor;  \
        g[offset+3]  += g[offset+11] * mult_factor;  \
        g[offset+2]  += g[offset+10] * mult_factor;  \
        g[offset+1]  += g[offset+9]  * mult_factor;   \
        g[offset+0]  += g[offset+8]  * mult_factor;   \
        g[offset+4]  += g[offset+8];                       \
        g[offset+2]  += g[offset+8];                       \
        g[offset+1]  += g[offset+8];                       \
        g[offset+5]  += g[offset+9];                       \
        g[offset+3]  += g[offset+9];                       \
        g[offset+2]  += g[offset+9];                       \
        g[offset+6]  += g[offset+10];                      \
        g[offset+4]  += g[offset+10];                      \
        g[offset+3]  += g[offset+10];                      \
        g[offset+7]  += g[offset+11];                      \
        g[offset+5]  += g[offset+11];                      \
        g[offset+4]  += g[offset+11];                      \
        g[offset+8]  += g[offset+12];                      \
        g[offset+6]  += g[offset+12];                      \
        g[offset+5]  += g[offset+12];                      \
        g[offset+9]  += g[offset+13];                      \
        g[offset+7]  += g[offset+13];                      \
        g[offset+6]  += g[offset+13];                      \
        g[offset+10] += g[offset+14];                      \
        g[offset+8]  += g[offset+14];                      \
        g[offset+7]  += g[offset+14];                      \
        g[offset+11] += g[offset+15];                      \
        g[offset+9]  += g[offset+15];                      \
        g[offset+8]  += g[offset+15];                      \
} while (0)


#define DIV_S4(mult_factor,offset) do {                                  \
        g[offset+16] += g[offset+31];                       \
        g[offset+15] += g[offset+30];                       \
        g[offset+14] += g[offset+29];                       \
        g[offset+13] += g[offset+28];                       \
        g[offset+12] += g[offset+27];                       \
        g[offset+11] += g[offset+26];                       \
        g[offset+10] += g[offset+25];                       \
        g[offset+9]  += g[offset+24];                       \
        g[offset+8]  += g[offset+23];                       \
        g[offset+7]  += g[offset+22];                       \
        g[offset+6]  += g[offset+21];                       \
        g[offset+5]  += g[offset+20];                       \
        g[offset+4]  += g[offset+19];                       \
        g[offset+3]  += g[offset+18];                       \
        g[offset+2]  += g[offset+17];                       \
        g[offset+1]  += g[offset+16];                       \
        g[offset+15] += g[offset+31] * mult_factor;  \
        g[offset+14] += g[offset+30] * mult_factor;  \
        g[offset+13] += g[offset+29] * mult_factor;  \
        g[offset+12] += g[offset+28] * mult_factor;  \
        g[offset+11] += g[offset+27] * mult_factor;  \
        g[offset+10] += g[offset+26] * mult_factor;  \
        g[offset+9]  += g[offset+25] * mult_factor;  \
        g[offset+8]  += g[offset+24] * mult_factor;  \
        g[offset+7]  += g[offset+23] * mult_factor;  \
        g[offset+6]  += g[offset+22] * mult_factor;  \
        g[offset+5]  += g[offset+21] * mult_factor;  \
        g[offset+4]  += g[offset+20] * mult_factor;  \
        g[offset+3]  += g[offset+19] * mult_factor;  \
        g[offset+2]  += g[offset+18] * mult_factor;  \
        g[offset+1]  += g[offset+17] * mult_factor;  \
        g[offset+0]  += g[offset+16] * mult_factor;  \
        g[offset+16] += g[offset+0];                       \
        g[offset+17] += g[offset+1];                       \
        g[offset+18] += g[offset+2];                       \
        g[offset+19] += g[offset+3];                       \
        g[offset+20] += g[offset+4];                       \
        g[offset+21] += g[offset+5];                       \
        g[offset+22] += g[offset+6];                       \
        g[offset+23] += g[offset+7];                       \
        g[offset+24] += g[offset+8];                       \
        g[offset+25] += g[offset+9];                       \
        g[offset+26] += g[offset+10];                      \
        g[offset+27] += g[offset+11];                      \
        g[offset+28] += g[offset+12];                      \
        g[offset+29] += g[offset+13];                      \
        g[offset+30] += g[offset+14];                      \
        g[offset+31] += g[offset+15];                      \
} while (0)


#define INV_DIV_S4(mult_factor,offset) do {                                  \
        g[offset+16] += g[offset+0];                       \
        g[offset+17] += g[offset+1];                       \
        g[offset+18] += g[offset+2];                       \
        g[offset+19] += g[offset+3];                       \
        g[offset+20] += g[offset+4];                       \
        g[offset+21] += g[offset+5];                       \
        g[offset+22] += g[offset+6];                       \
        g[offset+23] += g[offset+7];                       \
        g[offset+24] += g[offset+8];                       \
        g[offset+25] += g[offset+9];                       \
        g[offset+26] += g[offset+10];                      \
        g[offset+27] += g[offset+11];                      \
        g[offset+28] += g[offset+12];                      \
        g[offset+29] += g[offset+13];                      \
        g[offset+30] += g[offset+14];                      \
        g[offset+31] += g[offset+15];                      \
        g[offset+15] += g[offset+31] * mult_factor;  \
        g[offset+14] += g[offset+30] * mult_factor;  \
        g[offset+13] += g[offset+29] * mult_factor;  \
        g[offset+12] += g[offset+28] * mult_factor;  \
        g[offset+11] += g[offset+27] * mult_factor;  \
        g[offset+10] += g[offset+26] * mult_factor;  \
        g[offset+9]  += g[offset+25] * mult_factor;  \
        g[offset+8]  += g[offset+24] * mult_factor;  \
        g[offset+7]  += g[offset+23] * mult_factor;  \
        g[offset+6]  += g[offset+22] * mult_factor;  \
        g[offset+5]  += g[offset+21] * mult_factor;  \
        g[offset+4]  += g[offset+20] * mult_factor;  \
        g[offset+3]  += g[offset+19] * mult_factor;  \
        g[offset+2]  += g[offset+18] * mult_factor;  \
        g[offset+1]  += g[offset+17] * mult_factor;  \
        g[offset+0]  += g[offset+16] * mult_factor;  \
        g[offset+1]  += g[offset+16];                       \
        g[offset+2]  += g[offset+17];                       \
        g[offset+3]  += g[offset+18];                       \
        g[offset+4]  += g[offset+19];                       \
        g[offset+5]  += g[offset+20];                       \
        g[offset+6]  += g[offset+21];                       \
        g[offset+7]  += g[offset+22];                       \
        g[offset+8]  += g[offset+23];                       \
        g[offset+9]  += g[offset+24];                       \
        g[offset+10] += g[offset+25];                       \
        g[offset+11] += g[offset+26];                       \
        g[offset+12] += g[offset+27];                       \
        g[offset+13] += g[offset+28];                       \
        g[offset+14] += g[offset+29];                       \
        g[offset+15] += g[offset+30];                       \
        g[offset+16] += g[offset+31];                       \
} while (0)



#define DIV_S8(mult_factor,offset) do {                                            \
        for (int i = 256; i >= 1; --i) {                                       \
            g[offset+i] += g[offset+i+255];                            \
        }                                                                      \
        for (int i = 255; i >= 0; --i) {                                       \
            g[offset+i] += g[offset+i+256]*mult_factor; \
        }                                                                      \
        for (int i = 256; i <= 511; ++i) {                                     \
            g[offset+i] += g[offset+i-256];                            \
        }                                                                      \
} while (0)

#define INV_DIV_S8(mult_factor,offset) do {                                            \
        for (int i = 256; i <= 511; ++i) {                                     \
            g[offset+i] += g[offset+i-256];                            \
        }                                                                      \
        for (int i = 255; i >= 0; --i) {                                       \
            g[offset+i] += g[offset+i+256]*mult_factor; \
        }                                                                      \
        for (int i = 1; i <= 256; ++i) {                                       \
            g[offset+i] += g[offset+i+255];                            \
        }                                                                      \
} while (0)


#define DIV_S8_UR(mult_factor) do {                                    \
        poly[offset+256] ^= poly[offset+511];                          \
        poly[offset+255] ^= poly[offset+510];                          \
        poly[offset+254] ^= poly[offset+509];                          \
        poly[offset+253] ^= poly[offset+508];                          \
        poly[offset+252] ^= poly[offset+507];                          \
        poly[offset+251] ^= poly[offset+506];                          \
        poly[offset+250] ^= poly[offset+505];                          \
        poly[offset+249] ^= poly[offset+504];                          \
        poly[offset+248] ^= poly[offset+503];                          \
        poly[offset+247] ^= poly[offset+502];                          \
        poly[offset+246] ^= poly[offset+501];                          \
        poly[offset+245] ^= poly[offset+500];                          \
        poly[offset+244] ^= poly[offset+499];                          \
        poly[offset+243] ^= poly[offset+498];                          \
        poly[offset+242] ^= poly[offset+497];                          \
        poly[offset+241] ^= poly[offset+496];                          \
        poly[offset+240] ^= poly[offset+495];                          \
        poly[offset+239] ^= poly[offset+494];                          \
        poly[offset+238] ^= poly[offset+493];                          \
        poly[offset+237] ^= poly[offset+492];                          \
        poly[offset+236] ^= poly[offset+491];                          \
        poly[offset+235] ^= poly[offset+490];                          \
        poly[offset+234] ^= poly[offset+489];                          \
        poly[offset+233] ^= poly[offset+488];                          \
        poly[offset+232] ^= poly[offset+487];                          \
        poly[offset+231] ^= poly[offset+486];                          \
        poly[offset+230] ^= poly[offset+485];                          \
        poly[offset+229] ^= poly[offset+484];                          \
        poly[offset+228] ^= poly[offset+483];                          \
        poly[offset+227] ^= poly[offset+482];                          \
        poly[offset+226] ^= poly[offset+481];                          \
        poly[offset+225] ^= poly[offset+480];                          \
        poly[offset+224] ^= poly[offset+479];                          \
        poly[offset+223] ^= poly[offset+478];                          \
        poly[offset+222] ^= poly[offset+477];                          \
        poly[offset+221] ^= poly[offset+476];                          \
        poly[offset+220] ^= poly[offset+475];                          \
        poly[offset+219] ^= poly[offset+474];                          \
        poly[offset+218] ^= poly[offset+473];                          \
        poly[offset+217] ^= poly[offset+472];                          \
        poly[offset+216] ^= poly[offset+471];                          \
        poly[offset+215] ^= poly[offset+470];                          \
        poly[offset+214] ^= poly[offset+469];                          \
        poly[offset+213] ^= poly[offset+468];                          \
        poly[offset+212] ^= poly[offset+467];                          \
        poly[offset+211] ^= poly[offset+466];                          \
        poly[offset+210] ^= poly[offset+465];                          \
        poly[offset+209] ^= poly[offset+464];                          \
        poly[offset+208] ^= poly[offset+463];                          \
        poly[offset+207] ^= poly[offset+462];                          \
        poly[offset+206] ^= poly[offset+461];                          \
        poly[offset+205] ^= poly[offset+460];                          \
        poly[offset+204] ^= poly[offset+459];                          \
        poly[offset+203] ^= poly[offset+458];                          \
        poly[offset+202] ^= poly[offset+457];                          \
        poly[offset+201] ^= poly[offset+456];                          \
        poly[offset+200] ^= poly[offset+455];                          \
        poly[offset+199] ^= poly[offset+454];                          \
        poly[offset+198] ^= poly[offset+453];                          \
        poly[offset+197] ^= poly[offset+452];                          \
        poly[offset+196] ^= poly[offset+451];                          \
        poly[offset+195] ^= poly[offset+450];                          \
        poly[offset+194] ^= poly[offset+449];                          \
        poly[offset+193] ^= poly[offset+448];                          \
        poly[offset+192] ^= poly[offset+447];                          \
        poly[offset+191] ^= poly[offset+446];                          \
        poly[offset+190] ^= poly[offset+445];                          \
        poly[offset+189] ^= poly[offset+444];                          \
        poly[offset+188] ^= poly[offset+443];                          \
        poly[offset+187] ^= poly[offset+442];                          \
        poly[offset+186] ^= poly[offset+441];                          \
        poly[offset+185] ^= poly[offset+440];                          \
        poly[offset+184] ^= poly[offset+439];                          \
        poly[offset+183] ^= poly[offset+438];                          \
        poly[offset+182] ^= poly[offset+437];                          \
        poly[offset+181] ^= poly[offset+436];                          \
        poly[offset+180] ^= poly[offset+435];                          \
        poly[offset+179] ^= poly[offset+434];                          \
        poly[offset+178] ^= poly[offset+433];                          \
        poly[offset+177] ^= poly[offset+432];                          \
        poly[offset+176] ^= poly[offset+431];                          \
        poly[offset+175] ^= poly[offset+430];                          \
        poly[offset+174] ^= poly[offset+429];                          \
        poly[offset+173] ^= poly[offset+428];                          \
        poly[offset+172] ^= poly[offset+427];                          \
        poly[offset+171] ^= poly[offset+426];                          \
        poly[offset+170] ^= poly[offset+425];                          \
        poly[offset+169] ^= poly[offset+424];                          \
        poly[offset+168] ^= poly[offset+423];                          \
        poly[offset+167] ^= poly[offset+422];                          \
        poly[offset+166] ^= poly[offset+421];                          \
        poly[offset+165] ^= poly[offset+420];                          \
        poly[offset+164] ^= poly[offset+419];                          \
        poly[offset+163] ^= poly[offset+418];                          \
        poly[offset+162] ^= poly[offset+417];                          \
        poly[offset+161] ^= poly[offset+416];                          \
        poly[offset+160] ^= poly[offset+415];                          \
        poly[offset+159] ^= poly[offset+414];                          \
        poly[offset+158] ^= poly[offset+413];                          \
        poly[offset+157] ^= poly[offset+412];                          \
        poly[offset+156] ^= poly[offset+411];                          \
        poly[offset+155] ^= poly[offset+410];                          \
        poly[offset+154] ^= poly[offset+409];                          \
        poly[offset+153] ^= poly[offset+408];                          \
        poly[offset+152] ^= poly[offset+407];                          \
        poly[offset+151] ^= poly[offset+406];                          \
        poly[offset+150] ^= poly[offset+405];                          \
        poly[offset+149] ^= poly[offset+404];                          \
        poly[offset+148] ^= poly[offset+403];                          \
        poly[offset+147] ^= poly[offset+402];                          \
        poly[offset+146] ^= poly[offset+401];                          \
        poly[offset+145] ^= poly[offset+400];                          \
        poly[offset+144] ^= poly[offset+399];                          \
        poly[offset+143] ^= poly[offset+398];                          \
        poly[offset+142] ^= poly[offset+397];                          \
        poly[offset+141] ^= poly[offset+396];                          \
        poly[offset+140] ^= poly[offset+395];                          \
        poly[offset+139] ^= poly[offset+394];                          \
        poly[offset+138] ^= poly[offset+393];                          \
        poly[offset+137] ^= poly[offset+392];                          \
        poly[offset+136] ^= poly[offset+391];                          \
        poly[offset+135] ^= poly[offset+390];                          \
        poly[offset+134] ^= poly[offset+389];                          \
        poly[offset+133] ^= poly[offset+388];                          \
        poly[offset+132] ^= poly[offset+387];                          \
        poly[offset+131] ^= poly[offset+386];                          \
        poly[offset+130] ^= poly[offset+385];                          \
        poly[offset+129] ^= poly[offset+384];                          \
        poly[offset+128] ^= poly[offset+383];                          \
        poly[offset+127] ^= poly[offset+382];                          \
        poly[offset+126] ^= poly[offset+381];                          \
        poly[offset+125] ^= poly[offset+380];                          \
        poly[offset+124] ^= poly[offset+379];                          \
        poly[offset+123] ^= poly[offset+378];                          \
        poly[offset+122] ^= poly[offset+377];                          \
        poly[offset+121] ^= poly[offset+376];                          \
        poly[offset+120] ^= poly[offset+375];                          \
        poly[offset+119] ^= poly[offset+374];                          \
        poly[offset+118] ^= poly[offset+373];                          \
        poly[offset+117] ^= poly[offset+372];                          \
        poly[offset+116] ^= poly[offset+371];                          \
        poly[offset+115] ^= poly[offset+370];                          \
        poly[offset+114] ^= poly[offset+369];                          \
        poly[offset+113] ^= poly[offset+368];                          \
        poly[offset+112] ^= poly[offset+367];                          \
        poly[offset+111] ^= poly[offset+366];                          \
        poly[offset+110] ^= poly[offset+365];                          \
        poly[offset+109] ^= poly[offset+364];                          \
        poly[offset+108] ^= poly[offset+363];                          \
        poly[offset+107] ^= poly[offset+362];                          \
        poly[offset+106] ^= poly[offset+361];                          \
        poly[offset+105] ^= poly[offset+360];                          \
        poly[offset+104] ^= poly[offset+359];                          \
        poly[offset+103] ^= poly[offset+358];                          \
        poly[offset+102] ^= poly[offset+357];                          \
        poly[offset+101] ^= poly[offset+356];                          \
        poly[offset+100] ^= poly[offset+355];                          \
        poly[offset+99] ^= poly[offset+354];                          \
        poly[offset+98] ^= poly[offset+353];                          \
        poly[offset+97] ^= poly[offset+352];                          \
        poly[offset+96] ^= poly[offset+351];                          \
        poly[offset+95] ^= poly[offset+350];                          \
        poly[offset+94] ^= poly[offset+349];                          \
        poly[offset+93] ^= poly[offset+348];                          \
        poly[offset+92] ^= poly[offset+347];                          \
        poly[offset+91] ^= poly[offset+346];                          \
        poly[offset+90] ^= poly[offset+345];                          \
        poly[offset+89] ^= poly[offset+344];                          \
        poly[offset+88] ^= poly[offset+343];                          \
        poly[offset+87] ^= poly[offset+342];                          \
        poly[offset+86] ^= poly[offset+341];                          \
        poly[offset+85] ^= poly[offset+340];                          \
        poly[offset+84] ^= poly[offset+339];                          \
        poly[offset+83] ^= poly[offset+338];                          \
        poly[offset+82] ^= poly[offset+337];                          \
        poly[offset+81] ^= poly[offset+336];                          \
        poly[offset+80] ^= poly[offset+335];                          \
        poly[offset+79] ^= poly[offset+334];                          \
        poly[offset+78] ^= poly[offset+333];                          \
        poly[offset+77] ^= poly[offset+332];                          \
        poly[offset+76] ^= poly[offset+331];                          \
        poly[offset+75] ^= poly[offset+330];                          \
        poly[offset+74] ^= poly[offset+329];                          \
        poly[offset+73] ^= poly[offset+328];                          \
        poly[offset+72] ^= poly[offset+327];                          \
        poly[offset+71] ^= poly[offset+326];                          \
        poly[offset+70] ^= poly[offset+325];                          \
        poly[offset+69] ^= poly[offset+324];                          \
        poly[offset+68] ^= poly[offset+323];                          \
        poly[offset+67] ^= poly[offset+322];                          \
        poly[offset+66] ^= poly[offset+321];                          \
        poly[offset+65] ^= poly[offset+320];                          \
        poly[offset+64] ^= poly[offset+319];                          \
        poly[offset+63] ^= poly[offset+318];                          \
        poly[offset+62] ^= poly[offset+317];                          \
        poly[offset+61] ^= poly[offset+316];                          \
        poly[offset+60] ^= poly[offset+315];                          \
        poly[offset+59] ^= poly[offset+314];                          \
        poly[offset+58] ^= poly[offset+313];                          \
        poly[offset+57] ^= poly[offset+312];                          \
        poly[offset+56] ^= poly[offset+311];                          \
        poly[offset+55] ^= poly[offset+310];                          \
        poly[offset+54] ^= poly[offset+309];                          \
        poly[offset+53] ^= poly[offset+308];                          \
        poly[offset+52] ^= poly[offset+307];                          \
        poly[offset+51] ^= poly[offset+306];                          \
        poly[offset+50] ^= poly[offset+305];                          \
        poly[offset+49] ^= poly[offset+304];                          \
        poly[offset+48] ^= poly[offset+303];                          \
        poly[offset+47] ^= poly[offset+302];                          \
        poly[offset+46] ^= poly[offset+301];                          \
        poly[offset+45] ^= poly[offset+300];                          \
        poly[offset+44] ^= poly[offset+299];                          \
        poly[offset+43] ^= poly[offset+298];                          \
        poly[offset+42] ^= poly[offset+297];                          \
        poly[offset+41] ^= poly[offset+296];                          \
        poly[offset+40] ^= poly[offset+295];                          \
        poly[offset+39] ^= poly[offset+294];                          \
        poly[offset+38] ^= poly[offset+293];                          \
        poly[offset+37] ^= poly[offset+292];                          \
        poly[offset+36] ^= poly[offset+291];                          \
        poly[offset+35] ^= poly[offset+290];                          \
        poly[offset+34] ^= poly[offset+289];                          \
        poly[offset+33] ^= poly[offset+288];                          \
        poly[offset+32] ^= poly[offset+287];                          \
        poly[offset+31] ^= poly[offset+286];                          \
        poly[offset+30] ^= poly[offset+285];                          \
        poly[offset+29] ^= poly[offset+284];                          \
        poly[offset+28] ^= poly[offset+283];                          \
        poly[offset+27] ^= poly[offset+282];                          \
        poly[offset+26] ^= poly[offset+281];                          \
        poly[offset+25] ^= poly[offset+280];                          \
        poly[offset+24] ^= poly[offset+279];                          \
        poly[offset+23] ^= poly[offset+278];                          \
        poly[offset+22] ^= poly[offset+277];                          \
        poly[offset+21] ^= poly[offset+276];                          \
        poly[offset+20] ^= poly[offset+275];                          \
        poly[offset+19] ^= poly[offset+274];                          \
        poly[offset+18] ^= poly[offset+273];                          \
        poly[offset+17] ^= poly[offset+272];                          \
        poly[offset+16] ^= poly[offset+271];                          \
        poly[offset+15] ^= poly[offset+270];                          \
        poly[offset+14] ^= poly[offset+269];                          \
        poly[offset+13] ^= poly[offset+268];                          \
        poly[offset+12] ^= poly[offset+267];                          \
        poly[offset+11] ^= poly[offset+266];                          \
        poly[offset+10] ^= poly[offset+265];                          \
        poly[offset+9] ^= poly[offset+264];                          \
        poly[offset+8] ^= poly[offset+263];                          \
        poly[offset+7] ^= poly[offset+262];                          \
        poly[offset+6] ^= poly[offset+261];                          \
        poly[offset+5] ^= poly[offset+260];                          \
        poly[offset+4] ^= poly[offset+259];                          \
        poly[offset+3] ^= poly[offset+258];                          \
        poly[offset+2] ^= poly[offset+257];                          \
        poly[offset+1] ^= poly[offset+256];                          \
        poly[offset+0] ^= _gf2ext128_mul_sse(poly[offset+256], mult_factor);  \
        poly[offset+1] ^= _gf2ext128_mul_sse(poly[offset+257], mult_factor);  \
        poly[offset+2] ^= _gf2ext128_mul_sse(poly[offset+258], mult_factor);  \
        poly[offset+3] ^= _gf2ext128_mul_sse(poly[offset+259], mult_factor);  \
        poly[offset+4] ^= _gf2ext128_mul_sse(poly[offset+260], mult_factor);  \
        poly[offset+5] ^= _gf2ext128_mul_sse(poly[offset+261], mult_factor);  \
        poly[offset+6] ^= _gf2ext128_mul_sse(poly[offset+262], mult_factor);  \
        poly[offset+7] ^= _gf2ext128_mul_sse(poly[offset+263], mult_factor);  \
        poly[offset+8] ^= _gf2ext128_mul_sse(poly[offset+264], mult_factor);  \
        poly[offset+9] ^= _gf2ext128_mul_sse(poly[offset+265], mult_factor);  \
        poly[offset+10] ^= _gf2ext128_mul_sse(poly[offset+266], mult_factor);  \
        poly[offset+11] ^= _gf2ext128_mul_sse(poly[offset+267], mult_factor);  \
        poly[offset+12] ^= _gf2ext128_mul_sse(poly[offset+268], mult_factor);  \
        poly[offset+13] ^= _gf2ext128_mul_sse(poly[offset+269], mult_factor);  \
        poly[offset+14] ^= _gf2ext128_mul_sse(poly[offset+270], mult_factor);  \
        poly[offset+15] ^= _gf2ext128_mul_sse(poly[offset+271], mult_factor);  \
        poly[offset+16] ^= _gf2ext128_mul_sse(poly[offset+272], mult_factor);  \
        poly[offset+17] ^= _gf2ext128_mul_sse(poly[offset+273], mult_factor);  \
        poly[offset+18] ^= _gf2ext128_mul_sse(poly[offset+274], mult_factor);  \
        poly[offset+19] ^= _gf2ext128_mul_sse(poly[offset+275], mult_factor);  \
        poly[offset+20] ^= _gf2ext128_mul_sse(poly[offset+276], mult_factor);  \
        poly[offset+21] ^= _gf2ext128_mul_sse(poly[offset+277], mult_factor);  \
        poly[offset+22] ^= _gf2ext128_mul_sse(poly[offset+278], mult_factor);  \
        poly[offset+23] ^= _gf2ext128_mul_sse(poly[offset+279], mult_factor);  \
        poly[offset+24] ^= _gf2ext128_mul_sse(poly[offset+280], mult_factor);  \
        poly[offset+25] ^= _gf2ext128_mul_sse(poly[offset+281], mult_factor);  \
        poly[offset+26] ^= _gf2ext128_mul_sse(poly[offset+282], mult_factor);  \
        poly[offset+27] ^= _gf2ext128_mul_sse(poly[offset+283], mult_factor);  \
        poly[offset+28] ^= _gf2ext128_mul_sse(poly[offset+284], mult_factor);  \
        poly[offset+29] ^= _gf2ext128_mul_sse(poly[offset+285], mult_factor);  \
        poly[offset+30] ^= _gf2ext128_mul_sse(poly[offset+286], mult_factor);  \
        poly[offset+31] ^= _gf2ext128_mul_sse(poly[offset+287], mult_factor);  \
        poly[offset+32] ^= _gf2ext128_mul_sse(poly[offset+288], mult_factor);  \
        poly[offset+33] ^= _gf2ext128_mul_sse(poly[offset+289], mult_factor);  \
        poly[offset+34] ^= _gf2ext128_mul_sse(poly[offset+290], mult_factor);  \
        poly[offset+35] ^= _gf2ext128_mul_sse(poly[offset+291], mult_factor);  \
        poly[offset+36] ^= _gf2ext128_mul_sse(poly[offset+292], mult_factor);  \
        poly[offset+37] ^= _gf2ext128_mul_sse(poly[offset+293], mult_factor);  \
        poly[offset+38] ^= _gf2ext128_mul_sse(poly[offset+294], mult_factor);  \
        poly[offset+39] ^= _gf2ext128_mul_sse(poly[offset+295], mult_factor);  \
        poly[offset+40] ^= _gf2ext128_mul_sse(poly[offset+296], mult_factor);  \
        poly[offset+41] ^= _gf2ext128_mul_sse(poly[offset+297], mult_factor);  \
        poly[offset+42] ^= _gf2ext128_mul_sse(poly[offset+298], mult_factor);  \
        poly[offset+43] ^= _gf2ext128_mul_sse(poly[offset+299], mult_factor);  \
        poly[offset+44] ^= _gf2ext128_mul_sse(poly[offset+300], mult_factor);  \
        poly[offset+45] ^= _gf2ext128_mul_sse(poly[offset+301], mult_factor);  \
        poly[offset+46] ^= _gf2ext128_mul_sse(poly[offset+302], mult_factor);  \
        poly[offset+47] ^= _gf2ext128_mul_sse(poly[offset+303], mult_factor);  \
        poly[offset+48] ^= _gf2ext128_mul_sse(poly[offset+304], mult_factor);  \
        poly[offset+49] ^= _gf2ext128_mul_sse(poly[offset+305], mult_factor);  \
        poly[offset+50] ^= _gf2ext128_mul_sse(poly[offset+306], mult_factor);  \
        poly[offset+51] ^= _gf2ext128_mul_sse(poly[offset+307], mult_factor);  \
        poly[offset+52] ^= _gf2ext128_mul_sse(poly[offset+308], mult_factor);  \
        poly[offset+53] ^= _gf2ext128_mul_sse(poly[offset+309], mult_factor);  \
        poly[offset+54] ^= _gf2ext128_mul_sse(poly[offset+310], mult_factor);  \
        poly[offset+55] ^= _gf2ext128_mul_sse(poly[offset+311], mult_factor);  \
        poly[offset+56] ^= _gf2ext128_mul_sse(poly[offset+312], mult_factor);  \
        poly[offset+57] ^= _gf2ext128_mul_sse(poly[offset+313], mult_factor);  \
        poly[offset+58] ^= _gf2ext128_mul_sse(poly[offset+314], mult_factor);  \
        poly[offset+59] ^= _gf2ext128_mul_sse(poly[offset+315], mult_factor);  \
        poly[offset+60] ^= _gf2ext128_mul_sse(poly[offset+316], mult_factor);  \
        poly[offset+61] ^= _gf2ext128_mul_sse(poly[offset+317], mult_factor);  \
        poly[offset+62] ^= _gf2ext128_mul_sse(poly[offset+318], mult_factor);  \
        poly[offset+63] ^= _gf2ext128_mul_sse(poly[offset+319], mult_factor);  \
        poly[offset+64] ^= _gf2ext128_mul_sse(poly[offset+320], mult_factor);  \
        poly[offset+65] ^= _gf2ext128_mul_sse(poly[offset+321], mult_factor);  \
        poly[offset+66] ^= _gf2ext128_mul_sse(poly[offset+322], mult_factor);  \
        poly[offset+67] ^= _gf2ext128_mul_sse(poly[offset+323], mult_factor);  \
        poly[offset+68] ^= _gf2ext128_mul_sse(poly[offset+324], mult_factor);  \
        poly[offset+69] ^= _gf2ext128_mul_sse(poly[offset+325], mult_factor);  \
        poly[offset+70] ^= _gf2ext128_mul_sse(poly[offset+326], mult_factor);  \
        poly[offset+71] ^= _gf2ext128_mul_sse(poly[offset+327], mult_factor);  \
        poly[offset+72] ^= _gf2ext128_mul_sse(poly[offset+328], mult_factor);  \
        poly[offset+73] ^= _gf2ext128_mul_sse(poly[offset+329], mult_factor);  \
        poly[offset+74] ^= _gf2ext128_mul_sse(poly[offset+330], mult_factor);  \
        poly[offset+75] ^= _gf2ext128_mul_sse(poly[offset+331], mult_factor);  \
        poly[offset+76] ^= _gf2ext128_mul_sse(poly[offset+332], mult_factor);  \
        poly[offset+77] ^= _gf2ext128_mul_sse(poly[offset+333], mult_factor);  \
        poly[offset+78] ^= _gf2ext128_mul_sse(poly[offset+334], mult_factor);  \
        poly[offset+79] ^= _gf2ext128_mul_sse(poly[offset+335], mult_factor);  \
        poly[offset+80] ^= _gf2ext128_mul_sse(poly[offset+336], mult_factor);  \
        poly[offset+81] ^= _gf2ext128_mul_sse(poly[offset+337], mult_factor);  \
        poly[offset+82] ^= _gf2ext128_mul_sse(poly[offset+338], mult_factor);  \
        poly[offset+83] ^= _gf2ext128_mul_sse(poly[offset+339], mult_factor);  \
        poly[offset+84] ^= _gf2ext128_mul_sse(poly[offset+340], mult_factor);  \
        poly[offset+85] ^= _gf2ext128_mul_sse(poly[offset+341], mult_factor);  \
        poly[offset+86] ^= _gf2ext128_mul_sse(poly[offset+342], mult_factor);  \
        poly[offset+87] ^= _gf2ext128_mul_sse(poly[offset+343], mult_factor);  \
        poly[offset+88] ^= _gf2ext128_mul_sse(poly[offset+344], mult_factor);  \
        poly[offset+89] ^= _gf2ext128_mul_sse(poly[offset+345], mult_factor);  \
        poly[offset+90] ^= _gf2ext128_mul_sse(poly[offset+346], mult_factor);  \
        poly[offset+91] ^= _gf2ext128_mul_sse(poly[offset+347], mult_factor);  \
        poly[offset+92] ^= _gf2ext128_mul_sse(poly[offset+348], mult_factor);  \
        poly[offset+93] ^= _gf2ext128_mul_sse(poly[offset+349], mult_factor);  \
        poly[offset+94] ^= _gf2ext128_mul_sse(poly[offset+350], mult_factor);  \
        poly[offset+95] ^= _gf2ext128_mul_sse(poly[offset+351], mult_factor);  \
        poly[offset+96] ^= _gf2ext128_mul_sse(poly[offset+352], mult_factor);  \
        poly[offset+97] ^= _gf2ext128_mul_sse(poly[offset+353], mult_factor);  \
        poly[offset+98] ^= _gf2ext128_mul_sse(poly[offset+354], mult_factor);  \
        poly[offset+99] ^= _gf2ext128_mul_sse(poly[offset+355], mult_factor);  \
        poly[offset+100] ^= _gf2ext128_mul_sse(poly[offset+356], mult_factor);  \
        poly[offset+101] ^= _gf2ext128_mul_sse(poly[offset+357], mult_factor);  \
        poly[offset+102] ^= _gf2ext128_mul_sse(poly[offset+358], mult_factor);  \
        poly[offset+103] ^= _gf2ext128_mul_sse(poly[offset+359], mult_factor);  \
        poly[offset+104] ^= _gf2ext128_mul_sse(poly[offset+360], mult_factor);  \
        poly[offset+105] ^= _gf2ext128_mul_sse(poly[offset+361], mult_factor);  \
        poly[offset+106] ^= _gf2ext128_mul_sse(poly[offset+362], mult_factor);  \
        poly[offset+107] ^= _gf2ext128_mul_sse(poly[offset+363], mult_factor);  \
        poly[offset+108] ^= _gf2ext128_mul_sse(poly[offset+364], mult_factor);  \
        poly[offset+109] ^= _gf2ext128_mul_sse(poly[offset+365], mult_factor);  \
        poly[offset+110] ^= _gf2ext128_mul_sse(poly[offset+366], mult_factor);  \
        poly[offset+111] ^= _gf2ext128_mul_sse(poly[offset+367], mult_factor);  \
        poly[offset+112] ^= _gf2ext128_mul_sse(poly[offset+368], mult_factor);  \
        poly[offset+113] ^= _gf2ext128_mul_sse(poly[offset+369], mult_factor);  \
        poly[offset+114] ^= _gf2ext128_mul_sse(poly[offset+370], mult_factor);  \
        poly[offset+115] ^= _gf2ext128_mul_sse(poly[offset+371], mult_factor);  \
        poly[offset+116] ^= _gf2ext128_mul_sse(poly[offset+372], mult_factor);  \
        poly[offset+117] ^= _gf2ext128_mul_sse(poly[offset+373], mult_factor);  \
        poly[offset+118] ^= _gf2ext128_mul_sse(poly[offset+374], mult_factor);  \
        poly[offset+119] ^= _gf2ext128_mul_sse(poly[offset+375], mult_factor);  \
        poly[offset+120] ^= _gf2ext128_mul_sse(poly[offset+376], mult_factor);  \
        poly[offset+121] ^= _gf2ext128_mul_sse(poly[offset+377], mult_factor);  \
        poly[offset+122] ^= _gf2ext128_mul_sse(poly[offset+378], mult_factor);  \
        poly[offset+123] ^= _gf2ext128_mul_sse(poly[offset+379], mult_factor);  \
        poly[offset+124] ^= _gf2ext128_mul_sse(poly[offset+380], mult_factor);  \
        poly[offset+125] ^= _gf2ext128_mul_sse(poly[offset+381], mult_factor);  \
        poly[offset+126] ^= _gf2ext128_mul_sse(poly[offset+382], mult_factor);  \
        poly[offset+127] ^= _gf2ext128_mul_sse(poly[offset+383], mult_factor);  \
        poly[offset+128] ^= _gf2ext128_mul_sse(poly[offset+384], mult_factor);  \
        poly[offset+129] ^= _gf2ext128_mul_sse(poly[offset+385], mult_factor);  \
        poly[offset+130] ^= _gf2ext128_mul_sse(poly[offset+386], mult_factor);  \
        poly[offset+131] ^= _gf2ext128_mul_sse(poly[offset+387], mult_factor);  \
        poly[offset+132] ^= _gf2ext128_mul_sse(poly[offset+388], mult_factor);  \
        poly[offset+133] ^= _gf2ext128_mul_sse(poly[offset+389], mult_factor);  \
        poly[offset+134] ^= _gf2ext128_mul_sse(poly[offset+390], mult_factor);  \
        poly[offset+135] ^= _gf2ext128_mul_sse(poly[offset+391], mult_factor);  \
        poly[offset+136] ^= _gf2ext128_mul_sse(poly[offset+392], mult_factor);  \
        poly[offset+137] ^= _gf2ext128_mul_sse(poly[offset+393], mult_factor);  \
        poly[offset+138] ^= _gf2ext128_mul_sse(poly[offset+394], mult_factor);  \
        poly[offset+139] ^= _gf2ext128_mul_sse(poly[offset+395], mult_factor);  \
        poly[offset+140] ^= _gf2ext128_mul_sse(poly[offset+396], mult_factor);  \
        poly[offset+141] ^= _gf2ext128_mul_sse(poly[offset+397], mult_factor);  \
        poly[offset+142] ^= _gf2ext128_mul_sse(poly[offset+398], mult_factor);  \
        poly[offset+143] ^= _gf2ext128_mul_sse(poly[offset+399], mult_factor);  \
        poly[offset+144] ^= _gf2ext128_mul_sse(poly[offset+400], mult_factor);  \
        poly[offset+145] ^= _gf2ext128_mul_sse(poly[offset+401], mult_factor);  \
        poly[offset+146] ^= _gf2ext128_mul_sse(poly[offset+402], mult_factor);  \
        poly[offset+147] ^= _gf2ext128_mul_sse(poly[offset+403], mult_factor);  \
        poly[offset+148] ^= _gf2ext128_mul_sse(poly[offset+404], mult_factor);  \
        poly[offset+149] ^= _gf2ext128_mul_sse(poly[offset+405], mult_factor);  \
        poly[offset+150] ^= _gf2ext128_mul_sse(poly[offset+406], mult_factor);  \
        poly[offset+151] ^= _gf2ext128_mul_sse(poly[offset+407], mult_factor);  \
        poly[offset+152] ^= _gf2ext128_mul_sse(poly[offset+408], mult_factor);  \
        poly[offset+153] ^= _gf2ext128_mul_sse(poly[offset+409], mult_factor);  \
        poly[offset+154] ^= _gf2ext128_mul_sse(poly[offset+410], mult_factor);  \
        poly[offset+155] ^= _gf2ext128_mul_sse(poly[offset+411], mult_factor);  \
        poly[offset+156] ^= _gf2ext128_mul_sse(poly[offset+412], mult_factor);  \
        poly[offset+157] ^= _gf2ext128_mul_sse(poly[offset+413], mult_factor);  \
        poly[offset+158] ^= _gf2ext128_mul_sse(poly[offset+414], mult_factor);  \
        poly[offset+159] ^= _gf2ext128_mul_sse(poly[offset+415], mult_factor);  \
        poly[offset+160] ^= _gf2ext128_mul_sse(poly[offset+416], mult_factor);  \
        poly[offset+161] ^= _gf2ext128_mul_sse(poly[offset+417], mult_factor);  \
        poly[offset+162] ^= _gf2ext128_mul_sse(poly[offset+418], mult_factor);  \
        poly[offset+163] ^= _gf2ext128_mul_sse(poly[offset+419], mult_factor);  \
        poly[offset+164] ^= _gf2ext128_mul_sse(poly[offset+420], mult_factor);  \
        poly[offset+165] ^= _gf2ext128_mul_sse(poly[offset+421], mult_factor);  \
        poly[offset+166] ^= _gf2ext128_mul_sse(poly[offset+422], mult_factor);  \
        poly[offset+167] ^= _gf2ext128_mul_sse(poly[offset+423], mult_factor);  \
        poly[offset+168] ^= _gf2ext128_mul_sse(poly[offset+424], mult_factor);  \
        poly[offset+169] ^= _gf2ext128_mul_sse(poly[offset+425], mult_factor);  \
        poly[offset+170] ^= _gf2ext128_mul_sse(poly[offset+426], mult_factor);  \
        poly[offset+171] ^= _gf2ext128_mul_sse(poly[offset+427], mult_factor);  \
        poly[offset+172] ^= _gf2ext128_mul_sse(poly[offset+428], mult_factor);  \
        poly[offset+173] ^= _gf2ext128_mul_sse(poly[offset+429], mult_factor);  \
        poly[offset+174] ^= _gf2ext128_mul_sse(poly[offset+430], mult_factor);  \
        poly[offset+175] ^= _gf2ext128_mul_sse(poly[offset+431], mult_factor);  \
        poly[offset+176] ^= _gf2ext128_mul_sse(poly[offset+432], mult_factor);  \
        poly[offset+177] ^= _gf2ext128_mul_sse(poly[offset+433], mult_factor);  \
        poly[offset+178] ^= _gf2ext128_mul_sse(poly[offset+434], mult_factor);  \
        poly[offset+179] ^= _gf2ext128_mul_sse(poly[offset+435], mult_factor);  \
        poly[offset+180] ^= _gf2ext128_mul_sse(poly[offset+436], mult_factor);  \
        poly[offset+181] ^= _gf2ext128_mul_sse(poly[offset+437], mult_factor);  \
        poly[offset+182] ^= _gf2ext128_mul_sse(poly[offset+438], mult_factor);  \
        poly[offset+183] ^= _gf2ext128_mul_sse(poly[offset+439], mult_factor);  \
        poly[offset+184] ^= _gf2ext128_mul_sse(poly[offset+440], mult_factor);  \
        poly[offset+185] ^= _gf2ext128_mul_sse(poly[offset+441], mult_factor);  \
        poly[offset+186] ^= _gf2ext128_mul_sse(poly[offset+442], mult_factor);  \
        poly[offset+187] ^= _gf2ext128_mul_sse(poly[offset+443], mult_factor);  \
        poly[offset+188] ^= _gf2ext128_mul_sse(poly[offset+444], mult_factor);  \
        poly[offset+189] ^= _gf2ext128_mul_sse(poly[offset+445], mult_factor);  \
        poly[offset+190] ^= _gf2ext128_mul_sse(poly[offset+446], mult_factor);  \
        poly[offset+191] ^= _gf2ext128_mul_sse(poly[offset+447], mult_factor);  \
        poly[offset+192] ^= _gf2ext128_mul_sse(poly[offset+448], mult_factor);  \
        poly[offset+193] ^= _gf2ext128_mul_sse(poly[offset+449], mult_factor);  \
        poly[offset+194] ^= _gf2ext128_mul_sse(poly[offset+450], mult_factor);  \
        poly[offset+195] ^= _gf2ext128_mul_sse(poly[offset+451], mult_factor);  \
        poly[offset+196] ^= _gf2ext128_mul_sse(poly[offset+452], mult_factor);  \
        poly[offset+197] ^= _gf2ext128_mul_sse(poly[offset+453], mult_factor);  \
        poly[offset+198] ^= _gf2ext128_mul_sse(poly[offset+454], mult_factor);  \
        poly[offset+199] ^= _gf2ext128_mul_sse(poly[offset+455], mult_factor);  \
        poly[offset+200] ^= _gf2ext128_mul_sse(poly[offset+456], mult_factor);  \
        poly[offset+201] ^= _gf2ext128_mul_sse(poly[offset+457], mult_factor);  \
        poly[offset+202] ^= _gf2ext128_mul_sse(poly[offset+458], mult_factor);  \
        poly[offset+203] ^= _gf2ext128_mul_sse(poly[offset+459], mult_factor);  \
        poly[offset+204] ^= _gf2ext128_mul_sse(poly[offset+460], mult_factor);  \
        poly[offset+205] ^= _gf2ext128_mul_sse(poly[offset+461], mult_factor);  \
        poly[offset+206] ^= _gf2ext128_mul_sse(poly[offset+462], mult_factor);  \
        poly[offset+207] ^= _gf2ext128_mul_sse(poly[offset+463], mult_factor);  \
        poly[offset+208] ^= _gf2ext128_mul_sse(poly[offset+464], mult_factor);  \
        poly[offset+209] ^= _gf2ext128_mul_sse(poly[offset+465], mult_factor);  \
        poly[offset+210] ^= _gf2ext128_mul_sse(poly[offset+466], mult_factor);  \
        poly[offset+211] ^= _gf2ext128_mul_sse(poly[offset+467], mult_factor);  \
        poly[offset+212] ^= _gf2ext128_mul_sse(poly[offset+468], mult_factor);  \
        poly[offset+213] ^= _gf2ext128_mul_sse(poly[offset+469], mult_factor);  \
        poly[offset+214] ^= _gf2ext128_mul_sse(poly[offset+470], mult_factor);  \
        poly[offset+215] ^= _gf2ext128_mul_sse(poly[offset+471], mult_factor);  \
        poly[offset+216] ^= _gf2ext128_mul_sse(poly[offset+472], mult_factor);  \
        poly[offset+217] ^= _gf2ext128_mul_sse(poly[offset+473], mult_factor);  \
        poly[offset+218] ^= _gf2ext128_mul_sse(poly[offset+474], mult_factor);  \
        poly[offset+219] ^= _gf2ext128_mul_sse(poly[offset+475], mult_factor);  \
        poly[offset+220] ^= _gf2ext128_mul_sse(poly[offset+476], mult_factor);  \
        poly[offset+221] ^= _gf2ext128_mul_sse(poly[offset+477], mult_factor);  \
        poly[offset+222] ^= _gf2ext128_mul_sse(poly[offset+478], mult_factor);  \
        poly[offset+223] ^= _gf2ext128_mul_sse(poly[offset+479], mult_factor);  \
        poly[offset+224] ^= _gf2ext128_mul_sse(poly[offset+480], mult_factor);  \
        poly[offset+225] ^= _gf2ext128_mul_sse(poly[offset+481], mult_factor);  \
        poly[offset+226] ^= _gf2ext128_mul_sse(poly[offset+482], mult_factor);  \
        poly[offset+227] ^= _gf2ext128_mul_sse(poly[offset+483], mult_factor);  \
        poly[offset+228] ^= _gf2ext128_mul_sse(poly[offset+484], mult_factor);  \
        poly[offset+229] ^= _gf2ext128_mul_sse(poly[offset+485], mult_factor);  \
        poly[offset+230] ^= _gf2ext128_mul_sse(poly[offset+486], mult_factor);  \
        poly[offset+231] ^= _gf2ext128_mul_sse(poly[offset+487], mult_factor);  \
        poly[offset+232] ^= _gf2ext128_mul_sse(poly[offset+488], mult_factor);  \
        poly[offset+233] ^= _gf2ext128_mul_sse(poly[offset+489], mult_factor);  \
        poly[offset+234] ^= _gf2ext128_mul_sse(poly[offset+490], mult_factor);  \
        poly[offset+235] ^= _gf2ext128_mul_sse(poly[offset+491], mult_factor);  \
        poly[offset+236] ^= _gf2ext128_mul_sse(poly[offset+492], mult_factor);  \
        poly[offset+237] ^= _gf2ext128_mul_sse(poly[offset+493], mult_factor);  \
        poly[offset+238] ^= _gf2ext128_mul_sse(poly[offset+494], mult_factor);  \
        poly[offset+239] ^= _gf2ext128_mul_sse(poly[offset+495], mult_factor);  \
        poly[offset+240] ^= _gf2ext128_mul_sse(poly[offset+496], mult_factor);  \
        poly[offset+241] ^= _gf2ext128_mul_sse(poly[offset+497], mult_factor);  \
        poly[offset+242] ^= _gf2ext128_mul_sse(poly[offset+498], mult_factor);  \
        poly[offset+243] ^= _gf2ext128_mul_sse(poly[offset+499], mult_factor);  \
        poly[offset+244] ^= _gf2ext128_mul_sse(poly[offset+500], mult_factor);  \
        poly[offset+245] ^= _gf2ext128_mul_sse(poly[offset+501], mult_factor);  \
        poly[offset+246] ^= _gf2ext128_mul_sse(poly[offset+502], mult_factor);  \
        poly[offset+247] ^= _gf2ext128_mul_sse(poly[offset+503], mult_factor);  \
        poly[offset+248] ^= _gf2ext128_mul_sse(poly[offset+504], mult_factor);  \
        poly[offset+249] ^= _gf2ext128_mul_sse(poly[offset+505], mult_factor);  \
        poly[offset+250] ^= _gf2ext128_mul_sse(poly[offset+506], mult_factor);  \
        poly[offset+251] ^= _gf2ext128_mul_sse(poly[offset+507], mult_factor);  \
        poly[offset+252] ^= _gf2ext128_mul_sse(poly[offset+508], mult_factor);  \
        poly[offset+253] ^= _gf2ext128_mul_sse(poly[offset+509], mult_factor);  \
        poly[offset+254] ^= _gf2ext128_mul_sse(poly[offset+510], mult_factor);  \
        poly[offset+255] ^= _gf2ext128_mul_sse(poly[offset+511], mult_factor);  \
        poly[offset+256] ^= poly[offset+0];                             \
        poly[offset+257] ^= poly[offset+1];                             \
        poly[offset+258] ^= poly[offset+2];                             \
        poly[offset+259] ^= poly[offset+3];                             \
        poly[offset+260] ^= poly[offset+4];                             \
        poly[offset+261] ^= poly[offset+5];                             \
        poly[offset+262] ^= poly[offset+6];                             \
        poly[offset+263] ^= poly[offset+7];                             \
        poly[offset+264] ^= poly[offset+8];                             \
        poly[offset+265] ^= poly[offset+9];                             \
        poly[offset+266] ^= poly[offset+10];                             \
        poly[offset+267] ^= poly[offset+11];                             \
        poly[offset+268] ^= poly[offset+12];                             \
        poly[offset+269] ^= poly[offset+13];                             \
        poly[offset+270] ^= poly[offset+14];                             \
        poly[offset+271] ^= poly[offset+15];                             \
        poly[offset+272] ^= poly[offset+16];                             \
        poly[offset+273] ^= poly[offset+17];                             \
        poly[offset+274] ^= poly[offset+18];                             \
        poly[offset+275] ^= poly[offset+19];                             \
        poly[offset+276] ^= poly[offset+20];                             \
        poly[offset+277] ^= poly[offset+21];                             \
        poly[offset+278] ^= poly[offset+22];                             \
        poly[offset+279] ^= poly[offset+23];                             \
        poly[offset+280] ^= poly[offset+24];                             \
        poly[offset+281] ^= poly[offset+25];                             \
        poly[offset+282] ^= poly[offset+26];                             \
        poly[offset+283] ^= poly[offset+27];                             \
        poly[offset+284] ^= poly[offset+28];                             \
        poly[offset+285] ^= poly[offset+29];                             \
        poly[offset+286] ^= poly[offset+30];                             \
        poly[offset+287] ^= poly[offset+31];                             \
        poly[offset+288] ^= poly[offset+32];                             \
        poly[offset+289] ^= poly[offset+33];                             \
        poly[offset+290] ^= poly[offset+34];                             \
        poly[offset+291] ^= poly[offset+35];                             \
        poly[offset+292] ^= poly[offset+36];                             \
        poly[offset+293] ^= poly[offset+37];                             \
        poly[offset+294] ^= poly[offset+38];                             \
        poly[offset+295] ^= poly[offset+39];                             \
        poly[offset+296] ^= poly[offset+40];                             \
        poly[offset+297] ^= poly[offset+41];                             \
        poly[offset+298] ^= poly[offset+42];                             \
        poly[offset+299] ^= poly[offset+43];                             \
        poly[offset+300] ^= poly[offset+44];                             \
        poly[offset+301] ^= poly[offset+45];                             \
        poly[offset+302] ^= poly[offset+46];                             \
        poly[offset+303] ^= poly[offset+47];                             \
        poly[offset+304] ^= poly[offset+48];                             \
        poly[offset+305] ^= poly[offset+49];                             \
        poly[offset+306] ^= poly[offset+50];                             \
        poly[offset+307] ^= poly[offset+51];                             \
        poly[offset+308] ^= poly[offset+52];                             \
        poly[offset+309] ^= poly[offset+53];                             \
        poly[offset+310] ^= poly[offset+54];                             \
        poly[offset+311] ^= poly[offset+55];                             \
        poly[offset+312] ^= poly[offset+56];                             \
        poly[offset+313] ^= poly[offset+57];                             \
        poly[offset+314] ^= poly[offset+58];                             \
        poly[offset+315] ^= poly[offset+59];                             \
        poly[offset+316] ^= poly[offset+60];                             \
        poly[offset+317] ^= poly[offset+61];                             \
        poly[offset+318] ^= poly[offset+62];                             \
        poly[offset+319] ^= poly[offset+63];                             \
        poly[offset+320] ^= poly[offset+64];                             \
        poly[offset+321] ^= poly[offset+65];                             \
        poly[offset+322] ^= poly[offset+66];                             \
        poly[offset+323] ^= poly[offset+67];                             \
        poly[offset+324] ^= poly[offset+68];                             \
        poly[offset+325] ^= poly[offset+69];                             \
        poly[offset+326] ^= poly[offset+70];                             \
        poly[offset+327] ^= poly[offset+71];                             \
        poly[offset+328] ^= poly[offset+72];                             \
        poly[offset+329] ^= poly[offset+73];                             \
        poly[offset+330] ^= poly[offset+74];                             \
        poly[offset+331] ^= poly[offset+75];                             \
        poly[offset+332] ^= poly[offset+76];                             \
        poly[offset+333] ^= poly[offset+77];                             \
        poly[offset+334] ^= poly[offset+78];                             \
        poly[offset+335] ^= poly[offset+79];                             \
        poly[offset+336] ^= poly[offset+80];                             \
        poly[offset+337] ^= poly[offset+81];                             \
        poly[offset+338] ^= poly[offset+82];                             \
        poly[offset+339] ^= poly[offset+83];                             \
        poly[offset+340] ^= poly[offset+84];                             \
        poly[offset+341] ^= poly[offset+85];                             \
        poly[offset+342] ^= poly[offset+86];                             \
        poly[offset+343] ^= poly[offset+87];                             \
        poly[offset+344] ^= poly[offset+88];                             \
        poly[offset+345] ^= poly[offset+89];                             \
        poly[offset+346] ^= poly[offset+90];                             \
        poly[offset+347] ^= poly[offset+91];                             \
        poly[offset+348] ^= poly[offset+92];                             \
        poly[offset+349] ^= poly[offset+93];                             \
        poly[offset+350] ^= poly[offset+94];                             \
        poly[offset+351] ^= poly[offset+95];                             \
        poly[offset+352] ^= poly[offset+96];                             \
        poly[offset+353] ^= poly[offset+97];                             \
        poly[offset+354] ^= poly[offset+98];                             \
        poly[offset+355] ^= poly[offset+99];                             \
        poly[offset+356] ^= poly[offset+100];                             \
        poly[offset+357] ^= poly[offset+101];                             \
        poly[offset+358] ^= poly[offset+102];                             \
        poly[offset+359] ^= poly[offset+103];                             \
        poly[offset+360] ^= poly[offset+104];                             \
        poly[offset+361] ^= poly[offset+105];                             \
        poly[offset+362] ^= poly[offset+106];                             \
        poly[offset+363] ^= poly[offset+107];                             \
        poly[offset+364] ^= poly[offset+108];                             \
        poly[offset+365] ^= poly[offset+109];                             \
        poly[offset+366] ^= poly[offset+110];                             \
        poly[offset+367] ^= poly[offset+111];                             \
        poly[offset+368] ^= poly[offset+112];                             \
        poly[offset+369] ^= poly[offset+113];                             \
        poly[offset+370] ^= poly[offset+114];                             \
        poly[offset+371] ^= poly[offset+115];                             \
        poly[offset+372] ^= poly[offset+116];                             \
        poly[offset+373] ^= poly[offset+117];                             \
        poly[offset+374] ^= poly[offset+118];                             \
        poly[offset+375] ^= poly[offset+119];                             \
        poly[offset+376] ^= poly[offset+120];                             \
        poly[offset+377] ^= poly[offset+121];                             \
        poly[offset+378] ^= poly[offset+122];                             \
        poly[offset+379] ^= poly[offset+123];                             \
        poly[offset+380] ^= poly[offset+124];                             \
        poly[offset+381] ^= poly[offset+125];                             \
        poly[offset+382] ^= poly[offset+126];                             \
        poly[offset+383] ^= poly[offset+127];                             \
        poly[offset+384] ^= poly[offset+128];                             \
        poly[offset+385] ^= poly[offset+129];                             \
        poly[offset+386] ^= poly[offset+130];                             \
        poly[offset+387] ^= poly[offset+131];                             \
        poly[offset+388] ^= poly[offset+132];                             \
        poly[offset+389] ^= poly[offset+133];                             \
        poly[offset+390] ^= poly[offset+134];                             \
        poly[offset+391] ^= poly[offset+135];                             \
        poly[offset+392] ^= poly[offset+136];                             \
        poly[offset+393] ^= poly[offset+137];                             \
        poly[offset+394] ^= poly[offset+138];                             \
        poly[offset+395] ^= poly[offset+139];                             \
        poly[offset+396] ^= poly[offset+140];                             \
        poly[offset+397] ^= poly[offset+141];                             \
        poly[offset+398] ^= poly[offset+142];                             \
        poly[offset+399] ^= poly[offset+143];                             \
        poly[offset+400] ^= poly[offset+144];                             \
        poly[offset+401] ^= poly[offset+145];                             \
        poly[offset+402] ^= poly[offset+146];                             \
        poly[offset+403] ^= poly[offset+147];                             \
        poly[offset+404] ^= poly[offset+148];                             \
        poly[offset+405] ^= poly[offset+149];                             \
        poly[offset+406] ^= poly[offset+150];                             \
        poly[offset+407] ^= poly[offset+151];                             \
        poly[offset+408] ^= poly[offset+152];                             \
        poly[offset+409] ^= poly[offset+153];                             \
        poly[offset+410] ^= poly[offset+154];                             \
        poly[offset+411] ^= poly[offset+155];                             \
        poly[offset+412] ^= poly[offset+156];                             \
        poly[offset+413] ^= poly[offset+157];                             \
        poly[offset+414] ^= poly[offset+158];                             \
        poly[offset+415] ^= poly[offset+159];                             \
        poly[offset+416] ^= poly[offset+160];                             \
        poly[offset+417] ^= poly[offset+161];                             \
        poly[offset+418] ^= poly[offset+162];                             \
        poly[offset+419] ^= poly[offset+163];                             \
        poly[offset+420] ^= poly[offset+164];                             \
        poly[offset+421] ^= poly[offset+165];                             \
        poly[offset+422] ^= poly[offset+166];                             \
        poly[offset+423] ^= poly[offset+167];                             \
        poly[offset+424] ^= poly[offset+168];                             \
        poly[offset+425] ^= poly[offset+169];                             \
        poly[offset+426] ^= poly[offset+170];                             \
        poly[offset+427] ^= poly[offset+171];                             \
        poly[offset+428] ^= poly[offset+172];                             \
        poly[offset+429] ^= poly[offset+173];                             \
        poly[offset+430] ^= poly[offset+174];                             \
        poly[offset+431] ^= poly[offset+175];                             \
        poly[offset+432] ^= poly[offset+176];                             \
        poly[offset+433] ^= poly[offset+177];                             \
        poly[offset+434] ^= poly[offset+178];                             \
        poly[offset+435] ^= poly[offset+179];                             \
        poly[offset+436] ^= poly[offset+180];                             \
        poly[offset+437] ^= poly[offset+181];                             \
        poly[offset+438] ^= poly[offset+182];                             \
        poly[offset+439] ^= poly[offset+183];                             \
        poly[offset+440] ^= poly[offset+184];                             \
        poly[offset+441] ^= poly[offset+185];                             \
        poly[offset+442] ^= poly[offset+186];                             \
        poly[offset+443] ^= poly[offset+187];                             \
        poly[offset+444] ^= poly[offset+188];                             \
        poly[offset+445] ^= poly[offset+189];                             \
        poly[offset+446] ^= poly[offset+190];                             \
        poly[offset+447] ^= poly[offset+191];                             \
        poly[offset+448] ^= poly[offset+192];                             \
        poly[offset+449] ^= poly[offset+193];                             \
        poly[offset+450] ^= poly[offset+194];                             \
        poly[offset+451] ^= poly[offset+195];                             \
        poly[offset+452] ^= poly[offset+196];                             \
        poly[offset+453] ^= poly[offset+197];                             \
        poly[offset+454] ^= poly[offset+198];                             \
        poly[offset+455] ^= poly[offset+199];                             \
        poly[offset+456] ^= poly[offset+200];                             \
        poly[offset+457] ^= poly[offset+201];                             \
        poly[offset+458] ^= poly[offset+202];                             \
        poly[offset+459] ^= poly[offset+203];                             \
        poly[offset+460] ^= poly[offset+204];                             \
        poly[offset+461] ^= poly[offset+205];                             \
        poly[offset+462] ^= poly[offset+206];                             \
        poly[offset+463] ^= poly[offset+207];                             \
        poly[offset+464] ^= poly[offset+208];                             \
        poly[offset+465] ^= poly[offset+209];                             \
        poly[offset+466] ^= poly[offset+210];                             \
        poly[offset+467] ^= poly[offset+211];                             \
        poly[offset+468] ^= poly[offset+212];                             \
        poly[offset+469] ^= poly[offset+213];                             \
        poly[offset+470] ^= poly[offset+214];                             \
        poly[offset+471] ^= poly[offset+215];                             \
        poly[offset+472] ^= poly[offset+216];                             \
        poly[offset+473] ^= poly[offset+217];                             \
        poly[offset+474] ^= poly[offset+218];                             \
        poly[offset+475] ^= poly[offset+219];                             \
        poly[offset+476] ^= poly[offset+220];                             \
        poly[offset+477] ^= poly[offset+221];                             \
        poly[offset+478] ^= poly[offset+222];                             \
        poly[offset+479] ^= poly[offset+223];                             \
        poly[offset+480] ^= poly[offset+224];                             \
        poly[offset+481] ^= poly[offset+225];                             \
        poly[offset+482] ^= poly[offset+226];                             \
        poly[offset+483] ^= poly[offset+227];                             \
        poly[offset+484] ^= poly[offset+228];                             \
        poly[offset+485] ^= poly[offset+229];                             \
        poly[offset+486] ^= poly[offset+230];                             \
        poly[offset+487] ^= poly[offset+231];                             \
        poly[offset+488] ^= poly[offset+232];                             \
        poly[offset+489] ^= poly[offset+233];                             \
        poly[offset+490] ^= poly[offset+234];                             \
        poly[offset+491] ^= poly[offset+235];                             \
        poly[offset+492] ^= poly[offset+236];                             \
        poly[offset+493] ^= poly[offset+237];                             \
        poly[offset+494] ^= poly[offset+238];                             \
        poly[offset+495] ^= poly[offset+239];                             \
        poly[offset+496] ^= poly[offset+240];                             \
        poly[offset+497] ^= poly[offset+241];                             \
        poly[offset+498] ^= poly[offset+242];                             \
        poly[offset+499] ^= poly[offset+243];                             \
        poly[offset+500] ^= poly[offset+244];                             \
        poly[offset+501] ^= poly[offset+245];                             \
        poly[offset+502] ^= poly[offset+246];                             \
        poly[offset+503] ^= poly[offset+247];                             \
        poly[offset+504] ^= poly[offset+248];                             \
        poly[offset+505] ^= poly[offset+249];                             \
        poly[offset+506] ^= poly[offset+250];                             \
        poly[offset+507] ^= poly[offset+251];                             \
        poly[offset+508] ^= poly[offset+252];                             \
        poly[offset+509] ^= poly[offset+253];                             \
        poly[offset+510] ^= poly[offset+254];                             \
        poly[offset+511] ^= poly[offset+255];                             \
    } while (0)
    



#endif
