/* Auto-generated by dyadic/tune_dyadic — do not edit by hand. */
/* host: unknown */
/* date: Sat Aug  8 09:23:49 2026
 */
#ifndef DYADIC_TUNE_PARAMS_H_
#define DYADIC_TUNE_PARAMS_H_

#define DYADIC_TUNED_BLOCK (1u << 19)  /* 524288 elements, 8192 KB */

#endif
