// Install-time tuning for the dyadic AFFT cache chunk B (gf2x-style).
//
// Compares Dyadic only against itself over a power-of-two B sweep.
// Outputs:
//   1) Per-m optimum B table  -> dyadic_tune_table.txt (+ printed summary)
//   2) One compromise B       -> dyadic_tune_params.h  (library default)
//      chosen by min sum of relative slowdowns over m = 20..24:
//        score(B) = sum_m time(B,m) / min_{B'} time(B',m)
//
//   make tune          # from the C/ directory
//   make && ./main.out # uses the single tuned B (source=tuned)
//
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <time.h>

#include "dyadic_fft.h"

#define M_MIN 17
#define M_MAX 24
#define M_COUNT (M_MAX - M_MIN + 1)

static double now_ms(void){
    struct timespec ts;
    timespec_get(&ts, TIME_UTC);
    return ts.tv_sec * 1000.0 + ts.tv_nsec / 1e6;
}

static __m128i* random_poly(unsigned n){
    __m128i* fx = (__m128i*) aligned_alloc(64, sizeof(__m128i) * n);
    uint64_t* w = (uint64_t*) fx;
    for (unsigned i = 0; i < 2 * n; ++i)
        w[i] = ((uint64_t) rand() << 32) ^ (uint64_t) rand();
    return fx;
}

static double bench_dyadic(unsigned n, unsigned iters){
    double total = 0;
    for (unsigned it = 0; it < iters; ++it){
        __m128i* fx = random_poly(n);
        double t0 = now_ms();
        __m128i* evals = dyadic_fft_gf2128(fx, n);
        total += now_ms() - t0;
        free(fx);
        free(evals);
    }
    return total / iters;
}

static unsigned log2u(unsigned x){
    unsigned lg = 0;
    for (unsigned t = x; t > 1; t >>= 1) lg++;
    return lg;
}

static int write_tune_table(const unsigned* best_B, const double* best_ms,
                            const char* host){
    FILE* f = fopen("dyadic/dyadic_tune_table.txt", "w");
    if (!f){
        perror("fopen dyadic/dyadic_tune_table.txt");
        return 1;
    }
    time_t now = time(NULL);
    fprintf(f, "# Optimum cache block B (elements) per FFT size m = log2(n)\n");
    fprintf(f, "# host: %s\n", host && host[0] ? host : "unknown");
    fprintf(f, "# date: %s", ctime(&now));
    fprintf(f, "# B chosen as argmin over B in {2^12 .. 2^22} of mean Dyadic time\n");
    fprintf(f, "m\tn\tB\tlog2(B)\tB_KiB\ttime_ms\n");
    for (unsigned m = M_MIN; m <= M_MAX; ++m){
        unsigned i = m - M_MIN;
        unsigned B = best_B[i];
        fprintf(f, "%u\t%u\t%u\t%u\t%u\t%.4f\n",
                m, 1u << m, B, log2u(B), B / 64, best_ms[i]);
    }
    fclose(f);
    return 0;
}

static int write_tune_params(unsigned B, const unsigned* best_B,
                             const double* best_ms, const char* host){
    FILE* f = fopen("dyadic/dyadic_tune_params.h", "w");
    if (!f){
        perror("fopen dyadic/dyadic_tune_params.h");
        return 1;
    }
    time_t now = time(NULL);
    fprintf(f,
        "/* Auto-generated by dyadic/tune_dyadic — do not edit by hand. */\n"
        "/* host: %s */\n"
        "/* date: %s */\n"
        "#ifndef DYADIC_TUNE_PARAMS_H_\n"
        "#define DYADIC_TUNE_PARAMS_H_\n"
        "\n"
        "/* Single library default B (compromise over m=20..24). */\n"
        "#define DYADIC_TUNED_BLOCK (1u << %u)  /* %u elements, %u KB */\n"
        "\n"
        "/* Per-size optima from the same sweep (for tables / analysis):\n"
        " *   m   B=2^k   B_KiB   time_ms\n",
        host && host[0] ? host : "unknown",
        ctime(&now),
        log2u(B), B, B / 64);
    for (unsigned m = M_MIN; m <= M_MAX; ++m){
        unsigned i = m - M_MIN;
        unsigned Bm = best_B[i];
        fprintf(f, " *  %2u   2^%-2u   %5u   %.2f\n",
                m, log2u(Bm), Bm / 64, best_ms[i]);
    }
    fprintf(f,
        " * See also dyadic_tune_table.txt\n"
        " */\n"
        "\n"
        "#endif\n");
    fclose(f);
    return 0;
}

int main(void){
    srand((unsigned) time(NULL));
    const unsigned block_log[] = {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22};
    const unsigned n_blocks = sizeof(block_log) / sizeof(block_log[0]);
    const unsigned score_lo = 20, score_hi = 24;

    unsigned best_B[M_COUNT];
    double best_ms[M_COUNT];
    double score[sizeof(block_log) / sizeof(block_log[0])];
    for (unsigned b = 0; b < n_blocks; ++b) score[b] = 0.0;

    dyadic_fft_set_cache_block(0);
    printf("untuned default B = %u (%s)\n",
           dyadic_fft_get_cache_block(), dyadic_fft_cache_block_source());
    printf("sweep B = 2^12 .. 2^22; per-m optimum + one compromise B\n\n");

    printf("m");
    for (unsigned b = 0; b < n_blocks; ++b) printf("\t2^%u", block_log[b]);
    printf("\t(ms, mean; best on row marked *)\n");

    for (unsigned m = M_MIN; m <= M_MAX; ++m){
        unsigned n = 1u << m;
        unsigned iters = (m <= 19) ? 20 : (m <= 22 ? 8 : 4);

        double dy[sizeof(block_log) / sizeof(block_log[0])];
        unsigned best = 0;
        for (unsigned b = 0; b < n_blocks; ++b){
            dyadic_fft_set_cache_block(1u << block_log[b]);
            dy[b] = bench_dyadic(n, iters);
            if (dy[b] < dy[best]) best = b;
        }

        best_B[m - M_MIN] = 1u << block_log[best];
        best_ms[m - M_MIN] = dy[best];

        if (m >= score_lo && m <= score_hi){
            double tmin = dy[best];
            for (unsigned b = 0; b < n_blocks; ++b)
                score[b] += dy[b] / tmin;
        }

        printf("%u", m);
        for (unsigned b = 0; b < n_blocks; ++b)
            printf("\t%.2f%s", dy[b], b == best ? "*" : "");
        printf("\n");
    }

    unsigned best = 0;
    for (unsigned b = 1; b < n_blocks; ++b)
        if (score[b] < score[best]) best = b;
    unsigned B = 1u << block_log[best];

    printf("\n--- Optimum B by size (for paper table) ---\n");
    printf("m\tn\tB\tlog2(B)\tB_KiB\ttime_ms\n");
    for (unsigned m = M_MIN; m <= M_MAX; ++m){
        unsigned i = m - M_MIN;
        unsigned Bm = best_B[i];
        printf("%u\t%u\t%u\t%u\t%u\t%.2f\n",
               m, 1u << m, Bm, log2u(Bm), Bm / 64, best_ms[i]);
    }

    printf("\nrelative scores for single library B (m=%u..%u, lower better):",
           score_lo, score_hi);
    for (unsigned b = 0; b < n_blocks; ++b)
        printf("\t2^%u=%.3f%s", block_log[b], score[b], b == best ? "*" : "");
    printf("\n");

    const char* host = getenv("HOSTNAME");
    if (!host || !host[0]) host = getenv("HOST");
    if (write_tune_table(best_B, best_ms, host)) return 1;
    if (write_tune_params(B, best_B, best_ms, host)) return 1;

    printf("\nLibrary default B = %u elements (%u KB)  "
           "[min relative score, m=%u..%u]\n",
           B, B / 64, score_lo, score_hi);
    printf("Wrote dyadic/dyadic_tune_table.txt\n");
    printf("Wrote dyadic/dyadic_tune_params.h\n");
    printf("Rebuild with: make\n");
    return 0;
}
