#ifndef _DIV_BY_S_I_H_
#define _DIV_BY_S_I_H_

#define DIV_S0(mult_factor) do {                                \
    poly_offset[0] ^= _gf2ext128_mul_sse(poly_offset[1], (mult_factor));  \
    poly_offset[1] ^= poly_offset[0];                                    \
} while (0)

#define DIV_S1(mult_factor) do {                                \
        poly_offset[2] ^= poly_offset[3];                               \
        poly_offset[1] ^= _gf2ext128_mul_sse(poly_offset[3], mult_factor) ^ poly_offset[2];                                         \
        poly_offset[0] ^= _gf2ext128_mul_sse(poly_offset[2], mult_factor);                                                          \
        poly_offset[2] ^= poly_offset[0]; \
        poly_offset[3] ^= poly_offset[1]; \
} while (0)

#define DIV_S2(mult_factor) do {                                \
        poly_offset[4] ^= poly_offset[7];                       \
        poly_offset[3] ^= poly_offset[6];                       \
        poly_offset[2] ^= poly_offset[5];                       \
        poly_offset[1] ^= poly_offset[4];                       \
        poly_offset[3] ^= _gf2ext128_mul_sse(poly_offset[7], mult_factor);  \
        poly_offset[2] ^= _gf2ext128_mul_sse(poly_offset[6], mult_factor);  \
        poly_offset[1] ^= _gf2ext128_mul_sse(poly_offset[5], mult_factor);  \
        poly_offset[0] ^= _gf2ext128_mul_sse(poly_offset[4], mult_factor);  \
        poly_offset[4] ^= poly_offset[0];                       \
        poly_offset[5] ^= poly_offset[1];                       \
        poly_offset[6] ^= poly_offset[2];                       \
        poly_offset[7] ^= poly_offset[3];                       \
} while (0)


#define DIV_S3(mult_factor) do {                                \
        poly_offset[8]  ^= poly_offset[15];                       \
        poly_offset[9]  ^= poly_offset[15];                       \
        poly_offset[11] ^= poly_offset[15];                       \
        poly_offset[7]  ^= poly_offset[14];                       \
        poly_offset[8]  ^= poly_offset[14];                       \
        poly_offset[10] ^= poly_offset[14];                       \
        poly_offset[6]  ^= poly_offset[13];                       \
        poly_offset[7]  ^= poly_offset[13];                       \
        poly_offset[9]  ^= poly_offset[13];                       \
        poly_offset[5]  ^= poly_offset[12];                       \
        poly_offset[6]  ^= poly_offset[12];                       \
        poly_offset[8]  ^= poly_offset[12];                       \
        poly_offset[4]  ^= poly_offset[11];                       \
        poly_offset[5]  ^= poly_offset[11];                       \
        poly_offset[7]  ^= poly_offset[11];                       \
        poly_offset[3]  ^= poly_offset[10];                       \
        poly_offset[4]  ^= poly_offset[10];                       \
        poly_offset[6]  ^= poly_offset[10];                       \
        poly_offset[2]  ^= poly_offset[9];                       \
        poly_offset[3]  ^= poly_offset[9];                       \
        poly_offset[5]  ^= poly_offset[9];                       \
        poly_offset[1]  ^= poly_offset[8];                       \
        poly_offset[2]  ^= poly_offset[8];                       \
        poly_offset[4]  ^= poly_offset[8];                       \
        poly_offset[7] ^= _gf2ext128_mul_sse(poly_offset[15], mult_factor);  \
        poly_offset[6] ^= _gf2ext128_mul_sse(poly_offset[14], mult_factor);  \
        poly_offset[5] ^= _gf2ext128_mul_sse(poly_offset[13], mult_factor);  \
        poly_offset[4] ^= _gf2ext128_mul_sse(poly_offset[12], mult_factor);  \
        poly_offset[3] ^= _gf2ext128_mul_sse(poly_offset[11], mult_factor);  \
        poly_offset[2] ^= _gf2ext128_mul_sse(poly_offset[10], mult_factor);  \
        poly_offset[1] ^= _gf2ext128_mul_sse(poly_offset[9], mult_factor);   \
        poly_offset[0] ^= _gf2ext128_mul_sse(poly_offset[8], mult_factor);   \
        poly_offset[8]  ^= poly_offset[0];                       \
        poly_offset[9]  ^= poly_offset[1];                       \
        poly_offset[10] ^= poly_offset[2];                       \
        poly_offset[11] ^= poly_offset[3];                       \
        poly_offset[12] ^= poly_offset[4];                       \
        poly_offset[13] ^= poly_offset[5];                       \
        poly_offset[14] ^= poly_offset[6];                       \
        poly_offset[15] ^= poly_offset[7];                       \
} while (0)


#define DIV_S4(mult_factor) do {                                  \
        poly_offset[16] ^= poly_offset[31];                       \
        poly_offset[15] ^= poly_offset[30];                       \
        poly_offset[14] ^= poly_offset[29];                       \
        poly_offset[13] ^= poly_offset[28];                       \
        poly_offset[12] ^= poly_offset[27];                       \
        poly_offset[11] ^= poly_offset[26];                       \
        poly_offset[10] ^= poly_offset[25];                       \
        poly_offset[9]  ^= poly_offset[24];                       \
        poly_offset[8]  ^= poly_offset[23];                       \
        poly_offset[7]  ^= poly_offset[22];                       \
        poly_offset[6]  ^= poly_offset[21];                       \
        poly_offset[5]  ^= poly_offset[20];                       \
        poly_offset[4]  ^= poly_offset[19];                       \
        poly_offset[3]  ^= poly_offset[18];                       \
        poly_offset[2]  ^= poly_offset[17];                       \
        poly_offset[1]  ^= poly_offset[16];                       \
        poly_offset[15] ^= _gf2ext128_mul_sse(poly_offset[31], mult_factor);  \
        poly_offset[14] ^= _gf2ext128_mul_sse(poly_offset[30], mult_factor);  \
        poly_offset[13] ^= _gf2ext128_mul_sse(poly_offset[29], mult_factor);  \
        poly_offset[12] ^= _gf2ext128_mul_sse(poly_offset[28], mult_factor);  \
        poly_offset[11] ^= _gf2ext128_mul_sse(poly_offset[27], mult_factor);  \
        poly_offset[10] ^= _gf2ext128_mul_sse(poly_offset[26], mult_factor);  \
        poly_offset[9]  ^= _gf2ext128_mul_sse(poly_offset[25], mult_factor);  \
        poly_offset[8]  ^= _gf2ext128_mul_sse(poly_offset[24], mult_factor);  \
        poly_offset[7]  ^= _gf2ext128_mul_sse(poly_offset[23], mult_factor);  \
        poly_offset[6]  ^= _gf2ext128_mul_sse(poly_offset[22], mult_factor);  \
        poly_offset[5]  ^= _gf2ext128_mul_sse(poly_offset[21], mult_factor);  \
        poly_offset[4]  ^= _gf2ext128_mul_sse(poly_offset[20], mult_factor);  \
        poly_offset[3]  ^= _gf2ext128_mul_sse(poly_offset[19], mult_factor);  \
        poly_offset[2]  ^= _gf2ext128_mul_sse(poly_offset[18], mult_factor);  \
        poly_offset[1]  ^= _gf2ext128_mul_sse(poly_offset[17], mult_factor);  \
        poly_offset[0]  ^= _gf2ext128_mul_sse(poly_offset[16], mult_factor);  \
        poly_offset[16] ^= poly_offset[0];                       \
        poly_offset[17] ^= poly_offset[1];                       \
        poly_offset[18] ^= poly_offset[2];                       \
        poly_offset[19] ^= poly_offset[3];                       \
        poly_offset[20] ^= poly_offset[4];                       \
        poly_offset[21] ^= poly_offset[5];                       \
        poly_offset[22] ^= poly_offset[6];                       \
        poly_offset[23] ^= poly_offset[7];                       \
        poly_offset[24] ^= poly_offset[8];                       \
        poly_offset[25] ^= poly_offset[9];                       \
        poly_offset[26] ^= poly_offset[10];                      \
        poly_offset[27] ^= poly_offset[11];                      \
        poly_offset[28] ^= poly_offset[12];                      \
        poly_offset[29] ^= poly_offset[13];                      \
        poly_offset[30] ^= poly_offset[14];                      \
        poly_offset[31] ^= poly_offset[15];                      \
} while (0)


#define DIV_S8(mult_factor) do {                                            \
        for (int i = 256; i >= 1; --i) {                                       \
            poly_offset[i] ^= poly_offset[i + 255];                            \
        }                                                                      \
        for (int i = 255; i >= 0; --i) {                                       \
            poly_offset[i] ^= _gf2ext128_mul_sse(poly_offset[i + 256], mult_factor); \
        }                                                                      \
        for (int i = 256; i <= 511; ++i) {                                     \
            poly_offset[i] ^= poly_offset[i - 256];                            \
        }                                                                      \
} while (0)


#define DIV_S8_UR(mult_factor) do {                                    \
        poly_offset[256] ^= poly_offset[511];                          \
        poly_offset[255] ^= poly_offset[510];                          \
        poly_offset[254] ^= poly_offset[509];                          \
        poly_offset[253] ^= poly_offset[508];                          \
        poly_offset[252] ^= poly_offset[507];                          \
        poly_offset[251] ^= poly_offset[506];                          \
        poly_offset[250] ^= poly_offset[505];                          \
        poly_offset[249] ^= poly_offset[504];                          \
        poly_offset[248] ^= poly_offset[503];                          \
        poly_offset[247] ^= poly_offset[502];                          \
        poly_offset[246] ^= poly_offset[501];                          \
        poly_offset[245] ^= poly_offset[500];                          \
        poly_offset[244] ^= poly_offset[499];                          \
        poly_offset[243] ^= poly_offset[498];                          \
        poly_offset[242] ^= poly_offset[497];                          \
        poly_offset[241] ^= poly_offset[496];                          \
        poly_offset[240] ^= poly_offset[495];                          \
        poly_offset[239] ^= poly_offset[494];                          \
        poly_offset[238] ^= poly_offset[493];                          \
        poly_offset[237] ^= poly_offset[492];                          \
        poly_offset[236] ^= poly_offset[491];                          \
        poly_offset[235] ^= poly_offset[490];                          \
        poly_offset[234] ^= poly_offset[489];                          \
        poly_offset[233] ^= poly_offset[488];                          \
        poly_offset[232] ^= poly_offset[487];                          \
        poly_offset[231] ^= poly_offset[486];                          \
        poly_offset[230] ^= poly_offset[485];                          \
        poly_offset[229] ^= poly_offset[484];                          \
        poly_offset[228] ^= poly_offset[483];                          \
        poly_offset[227] ^= poly_offset[482];                          \
        poly_offset[226] ^= poly_offset[481];                          \
        poly_offset[225] ^= poly_offset[480];                          \
        poly_offset[224] ^= poly_offset[479];                          \
        poly_offset[223] ^= poly_offset[478];                          \
        poly_offset[222] ^= poly_offset[477];                          \
        poly_offset[221] ^= poly_offset[476];                          \
        poly_offset[220] ^= poly_offset[475];                          \
        poly_offset[219] ^= poly_offset[474];                          \
        poly_offset[218] ^= poly_offset[473];                          \
        poly_offset[217] ^= poly_offset[472];                          \
        poly_offset[216] ^= poly_offset[471];                          \
        poly_offset[215] ^= poly_offset[470];                          \
        poly_offset[214] ^= poly_offset[469];                          \
        poly_offset[213] ^= poly_offset[468];                          \
        poly_offset[212] ^= poly_offset[467];                          \
        poly_offset[211] ^= poly_offset[466];                          \
        poly_offset[210] ^= poly_offset[465];                          \
        poly_offset[209] ^= poly_offset[464];                          \
        poly_offset[208] ^= poly_offset[463];                          \
        poly_offset[207] ^= poly_offset[462];                          \
        poly_offset[206] ^= poly_offset[461];                          \
        poly_offset[205] ^= poly_offset[460];                          \
        poly_offset[204] ^= poly_offset[459];                          \
        poly_offset[203] ^= poly_offset[458];                          \
        poly_offset[202] ^= poly_offset[457];                          \
        poly_offset[201] ^= poly_offset[456];                          \
        poly_offset[200] ^= poly_offset[455];                          \
        poly_offset[199] ^= poly_offset[454];                          \
        poly_offset[198] ^= poly_offset[453];                          \
        poly_offset[197] ^= poly_offset[452];                          \
        poly_offset[196] ^= poly_offset[451];                          \
        poly_offset[195] ^= poly_offset[450];                          \
        poly_offset[194] ^= poly_offset[449];                          \
        poly_offset[193] ^= poly_offset[448];                          \
        poly_offset[192] ^= poly_offset[447];                          \
        poly_offset[191] ^= poly_offset[446];                          \
        poly_offset[190] ^= poly_offset[445];                          \
        poly_offset[189] ^= poly_offset[444];                          \
        poly_offset[188] ^= poly_offset[443];                          \
        poly_offset[187] ^= poly_offset[442];                          \
        poly_offset[186] ^= poly_offset[441];                          \
        poly_offset[185] ^= poly_offset[440];                          \
        poly_offset[184] ^= poly_offset[439];                          \
        poly_offset[183] ^= poly_offset[438];                          \
        poly_offset[182] ^= poly_offset[437];                          \
        poly_offset[181] ^= poly_offset[436];                          \
        poly_offset[180] ^= poly_offset[435];                          \
        poly_offset[179] ^= poly_offset[434];                          \
        poly_offset[178] ^= poly_offset[433];                          \
        poly_offset[177] ^= poly_offset[432];                          \
        poly_offset[176] ^= poly_offset[431];                          \
        poly_offset[175] ^= poly_offset[430];                          \
        poly_offset[174] ^= poly_offset[429];                          \
        poly_offset[173] ^= poly_offset[428];                          \
        poly_offset[172] ^= poly_offset[427];                          \
        poly_offset[171] ^= poly_offset[426];                          \
        poly_offset[170] ^= poly_offset[425];                          \
        poly_offset[169] ^= poly_offset[424];                          \
        poly_offset[168] ^= poly_offset[423];                          \
        poly_offset[167] ^= poly_offset[422];                          \
        poly_offset[166] ^= poly_offset[421];                          \
        poly_offset[165] ^= poly_offset[420];                          \
        poly_offset[164] ^= poly_offset[419];                          \
        poly_offset[163] ^= poly_offset[418];                          \
        poly_offset[162] ^= poly_offset[417];                          \
        poly_offset[161] ^= poly_offset[416];                          \
        poly_offset[160] ^= poly_offset[415];                          \
        poly_offset[159] ^= poly_offset[414];                          \
        poly_offset[158] ^= poly_offset[413];                          \
        poly_offset[157] ^= poly_offset[412];                          \
        poly_offset[156] ^= poly_offset[411];                          \
        poly_offset[155] ^= poly_offset[410];                          \
        poly_offset[154] ^= poly_offset[409];                          \
        poly_offset[153] ^= poly_offset[408];                          \
        poly_offset[152] ^= poly_offset[407];                          \
        poly_offset[151] ^= poly_offset[406];                          \
        poly_offset[150] ^= poly_offset[405];                          \
        poly_offset[149] ^= poly_offset[404];                          \
        poly_offset[148] ^= poly_offset[403];                          \
        poly_offset[147] ^= poly_offset[402];                          \
        poly_offset[146] ^= poly_offset[401];                          \
        poly_offset[145] ^= poly_offset[400];                          \
        poly_offset[144] ^= poly_offset[399];                          \
        poly_offset[143] ^= poly_offset[398];                          \
        poly_offset[142] ^= poly_offset[397];                          \
        poly_offset[141] ^= poly_offset[396];                          \
        poly_offset[140] ^= poly_offset[395];                          \
        poly_offset[139] ^= poly_offset[394];                          \
        poly_offset[138] ^= poly_offset[393];                          \
        poly_offset[137] ^= poly_offset[392];                          \
        poly_offset[136] ^= poly_offset[391];                          \
        poly_offset[135] ^= poly_offset[390];                          \
        poly_offset[134] ^= poly_offset[389];                          \
        poly_offset[133] ^= poly_offset[388];                          \
        poly_offset[132] ^= poly_offset[387];                          \
        poly_offset[131] ^= poly_offset[386];                          \
        poly_offset[130] ^= poly_offset[385];                          \
        poly_offset[129] ^= poly_offset[384];                          \
        poly_offset[128] ^= poly_offset[383];                          \
        poly_offset[127] ^= poly_offset[382];                          \
        poly_offset[126] ^= poly_offset[381];                          \
        poly_offset[125] ^= poly_offset[380];                          \
        poly_offset[124] ^= poly_offset[379];                          \
        poly_offset[123] ^= poly_offset[378];                          \
        poly_offset[122] ^= poly_offset[377];                          \
        poly_offset[121] ^= poly_offset[376];                          \
        poly_offset[120] ^= poly_offset[375];                          \
        poly_offset[119] ^= poly_offset[374];                          \
        poly_offset[118] ^= poly_offset[373];                          \
        poly_offset[117] ^= poly_offset[372];                          \
        poly_offset[116] ^= poly_offset[371];                          \
        poly_offset[115] ^= poly_offset[370];                          \
        poly_offset[114] ^= poly_offset[369];                          \
        poly_offset[113] ^= poly_offset[368];                          \
        poly_offset[112] ^= poly_offset[367];                          \
        poly_offset[111] ^= poly_offset[366];                          \
        poly_offset[110] ^= poly_offset[365];                          \
        poly_offset[109] ^= poly_offset[364];                          \
        poly_offset[108] ^= poly_offset[363];                          \
        poly_offset[107] ^= poly_offset[362];                          \
        poly_offset[106] ^= poly_offset[361];                          \
        poly_offset[105] ^= poly_offset[360];                          \
        poly_offset[104] ^= poly_offset[359];                          \
        poly_offset[103] ^= poly_offset[358];                          \
        poly_offset[102] ^= poly_offset[357];                          \
        poly_offset[101] ^= poly_offset[356];                          \
        poly_offset[100] ^= poly_offset[355];                          \
        poly_offset[99] ^= poly_offset[354];                          \
        poly_offset[98] ^= poly_offset[353];                          \
        poly_offset[97] ^= poly_offset[352];                          \
        poly_offset[96] ^= poly_offset[351];                          \
        poly_offset[95] ^= poly_offset[350];                          \
        poly_offset[94] ^= poly_offset[349];                          \
        poly_offset[93] ^= poly_offset[348];                          \
        poly_offset[92] ^= poly_offset[347];                          \
        poly_offset[91] ^= poly_offset[346];                          \
        poly_offset[90] ^= poly_offset[345];                          \
        poly_offset[89] ^= poly_offset[344];                          \
        poly_offset[88] ^= poly_offset[343];                          \
        poly_offset[87] ^= poly_offset[342];                          \
        poly_offset[86] ^= poly_offset[341];                          \
        poly_offset[85] ^= poly_offset[340];                          \
        poly_offset[84] ^= poly_offset[339];                          \
        poly_offset[83] ^= poly_offset[338];                          \
        poly_offset[82] ^= poly_offset[337];                          \
        poly_offset[81] ^= poly_offset[336];                          \
        poly_offset[80] ^= poly_offset[335];                          \
        poly_offset[79] ^= poly_offset[334];                          \
        poly_offset[78] ^= poly_offset[333];                          \
        poly_offset[77] ^= poly_offset[332];                          \
        poly_offset[76] ^= poly_offset[331];                          \
        poly_offset[75] ^= poly_offset[330];                          \
        poly_offset[74] ^= poly_offset[329];                          \
        poly_offset[73] ^= poly_offset[328];                          \
        poly_offset[72] ^= poly_offset[327];                          \
        poly_offset[71] ^= poly_offset[326];                          \
        poly_offset[70] ^= poly_offset[325];                          \
        poly_offset[69] ^= poly_offset[324];                          \
        poly_offset[68] ^= poly_offset[323];                          \
        poly_offset[67] ^= poly_offset[322];                          \
        poly_offset[66] ^= poly_offset[321];                          \
        poly_offset[65] ^= poly_offset[320];                          \
        poly_offset[64] ^= poly_offset[319];                          \
        poly_offset[63] ^= poly_offset[318];                          \
        poly_offset[62] ^= poly_offset[317];                          \
        poly_offset[61] ^= poly_offset[316];                          \
        poly_offset[60] ^= poly_offset[315];                          \
        poly_offset[59] ^= poly_offset[314];                          \
        poly_offset[58] ^= poly_offset[313];                          \
        poly_offset[57] ^= poly_offset[312];                          \
        poly_offset[56] ^= poly_offset[311];                          \
        poly_offset[55] ^= poly_offset[310];                          \
        poly_offset[54] ^= poly_offset[309];                          \
        poly_offset[53] ^= poly_offset[308];                          \
        poly_offset[52] ^= poly_offset[307];                          \
        poly_offset[51] ^= poly_offset[306];                          \
        poly_offset[50] ^= poly_offset[305];                          \
        poly_offset[49] ^= poly_offset[304];                          \
        poly_offset[48] ^= poly_offset[303];                          \
        poly_offset[47] ^= poly_offset[302];                          \
        poly_offset[46] ^= poly_offset[301];                          \
        poly_offset[45] ^= poly_offset[300];                          \
        poly_offset[44] ^= poly_offset[299];                          \
        poly_offset[43] ^= poly_offset[298];                          \
        poly_offset[42] ^= poly_offset[297];                          \
        poly_offset[41] ^= poly_offset[296];                          \
        poly_offset[40] ^= poly_offset[295];                          \
        poly_offset[39] ^= poly_offset[294];                          \
        poly_offset[38] ^= poly_offset[293];                          \
        poly_offset[37] ^= poly_offset[292];                          \
        poly_offset[36] ^= poly_offset[291];                          \
        poly_offset[35] ^= poly_offset[290];                          \
        poly_offset[34] ^= poly_offset[289];                          \
        poly_offset[33] ^= poly_offset[288];                          \
        poly_offset[32] ^= poly_offset[287];                          \
        poly_offset[31] ^= poly_offset[286];                          \
        poly_offset[30] ^= poly_offset[285];                          \
        poly_offset[29] ^= poly_offset[284];                          \
        poly_offset[28] ^= poly_offset[283];                          \
        poly_offset[27] ^= poly_offset[282];                          \
        poly_offset[26] ^= poly_offset[281];                          \
        poly_offset[25] ^= poly_offset[280];                          \
        poly_offset[24] ^= poly_offset[279];                          \
        poly_offset[23] ^= poly_offset[278];                          \
        poly_offset[22] ^= poly_offset[277];                          \
        poly_offset[21] ^= poly_offset[276];                          \
        poly_offset[20] ^= poly_offset[275];                          \
        poly_offset[19] ^= poly_offset[274];                          \
        poly_offset[18] ^= poly_offset[273];                          \
        poly_offset[17] ^= poly_offset[272];                          \
        poly_offset[16] ^= poly_offset[271];                          \
        poly_offset[15] ^= poly_offset[270];                          \
        poly_offset[14] ^= poly_offset[269];                          \
        poly_offset[13] ^= poly_offset[268];                          \
        poly_offset[12] ^= poly_offset[267];                          \
        poly_offset[11] ^= poly_offset[266];                          \
        poly_offset[10] ^= poly_offset[265];                          \
        poly_offset[9] ^= poly_offset[264];                          \
        poly_offset[8] ^= poly_offset[263];                          \
        poly_offset[7] ^= poly_offset[262];                          \
        poly_offset[6] ^= poly_offset[261];                          \
        poly_offset[5] ^= poly_offset[260];                          \
        poly_offset[4] ^= poly_offset[259];                          \
        poly_offset[3] ^= poly_offset[258];                          \
        poly_offset[2] ^= poly_offset[257];                          \
        poly_offset[1] ^= poly_offset[256];                          \
        poly_offset[0] ^= _gf2ext128_mul_sse(poly_offset[256], mult_factor);  \
        poly_offset[1] ^= _gf2ext128_mul_sse(poly_offset[257], mult_factor);  \
        poly_offset[2] ^= _gf2ext128_mul_sse(poly_offset[258], mult_factor);  \
        poly_offset[3] ^= _gf2ext128_mul_sse(poly_offset[259], mult_factor);  \
        poly_offset[4] ^= _gf2ext128_mul_sse(poly_offset[260], mult_factor);  \
        poly_offset[5] ^= _gf2ext128_mul_sse(poly_offset[261], mult_factor);  \
        poly_offset[6] ^= _gf2ext128_mul_sse(poly_offset[262], mult_factor);  \
        poly_offset[7] ^= _gf2ext128_mul_sse(poly_offset[263], mult_factor);  \
        poly_offset[8] ^= _gf2ext128_mul_sse(poly_offset[264], mult_factor);  \
        poly_offset[9] ^= _gf2ext128_mul_sse(poly_offset[265], mult_factor);  \
        poly_offset[10] ^= _gf2ext128_mul_sse(poly_offset[266], mult_factor);  \
        poly_offset[11] ^= _gf2ext128_mul_sse(poly_offset[267], mult_factor);  \
        poly_offset[12] ^= _gf2ext128_mul_sse(poly_offset[268], mult_factor);  \
        poly_offset[13] ^= _gf2ext128_mul_sse(poly_offset[269], mult_factor);  \
        poly_offset[14] ^= _gf2ext128_mul_sse(poly_offset[270], mult_factor);  \
        poly_offset[15] ^= _gf2ext128_mul_sse(poly_offset[271], mult_factor);  \
        poly_offset[16] ^= _gf2ext128_mul_sse(poly_offset[272], mult_factor);  \
        poly_offset[17] ^= _gf2ext128_mul_sse(poly_offset[273], mult_factor);  \
        poly_offset[18] ^= _gf2ext128_mul_sse(poly_offset[274], mult_factor);  \
        poly_offset[19] ^= _gf2ext128_mul_sse(poly_offset[275], mult_factor);  \
        poly_offset[20] ^= _gf2ext128_mul_sse(poly_offset[276], mult_factor);  \
        poly_offset[21] ^= _gf2ext128_mul_sse(poly_offset[277], mult_factor);  \
        poly_offset[22] ^= _gf2ext128_mul_sse(poly_offset[278], mult_factor);  \
        poly_offset[23] ^= _gf2ext128_mul_sse(poly_offset[279], mult_factor);  \
        poly_offset[24] ^= _gf2ext128_mul_sse(poly_offset[280], mult_factor);  \
        poly_offset[25] ^= _gf2ext128_mul_sse(poly_offset[281], mult_factor);  \
        poly_offset[26] ^= _gf2ext128_mul_sse(poly_offset[282], mult_factor);  \
        poly_offset[27] ^= _gf2ext128_mul_sse(poly_offset[283], mult_factor);  \
        poly_offset[28] ^= _gf2ext128_mul_sse(poly_offset[284], mult_factor);  \
        poly_offset[29] ^= _gf2ext128_mul_sse(poly_offset[285], mult_factor);  \
        poly_offset[30] ^= _gf2ext128_mul_sse(poly_offset[286], mult_factor);  \
        poly_offset[31] ^= _gf2ext128_mul_sse(poly_offset[287], mult_factor);  \
        poly_offset[32] ^= _gf2ext128_mul_sse(poly_offset[288], mult_factor);  \
        poly_offset[33] ^= _gf2ext128_mul_sse(poly_offset[289], mult_factor);  \
        poly_offset[34] ^= _gf2ext128_mul_sse(poly_offset[290], mult_factor);  \
        poly_offset[35] ^= _gf2ext128_mul_sse(poly_offset[291], mult_factor);  \
        poly_offset[36] ^= _gf2ext128_mul_sse(poly_offset[292], mult_factor);  \
        poly_offset[37] ^= _gf2ext128_mul_sse(poly_offset[293], mult_factor);  \
        poly_offset[38] ^= _gf2ext128_mul_sse(poly_offset[294], mult_factor);  \
        poly_offset[39] ^= _gf2ext128_mul_sse(poly_offset[295], mult_factor);  \
        poly_offset[40] ^= _gf2ext128_mul_sse(poly_offset[296], mult_factor);  \
        poly_offset[41] ^= _gf2ext128_mul_sse(poly_offset[297], mult_factor);  \
        poly_offset[42] ^= _gf2ext128_mul_sse(poly_offset[298], mult_factor);  \
        poly_offset[43] ^= _gf2ext128_mul_sse(poly_offset[299], mult_factor);  \
        poly_offset[44] ^= _gf2ext128_mul_sse(poly_offset[300], mult_factor);  \
        poly_offset[45] ^= _gf2ext128_mul_sse(poly_offset[301], mult_factor);  \
        poly_offset[46] ^= _gf2ext128_mul_sse(poly_offset[302], mult_factor);  \
        poly_offset[47] ^= _gf2ext128_mul_sse(poly_offset[303], mult_factor);  \
        poly_offset[48] ^= _gf2ext128_mul_sse(poly_offset[304], mult_factor);  \
        poly_offset[49] ^= _gf2ext128_mul_sse(poly_offset[305], mult_factor);  \
        poly_offset[50] ^= _gf2ext128_mul_sse(poly_offset[306], mult_factor);  \
        poly_offset[51] ^= _gf2ext128_mul_sse(poly_offset[307], mult_factor);  \
        poly_offset[52] ^= _gf2ext128_mul_sse(poly_offset[308], mult_factor);  \
        poly_offset[53] ^= _gf2ext128_mul_sse(poly_offset[309], mult_factor);  \
        poly_offset[54] ^= _gf2ext128_mul_sse(poly_offset[310], mult_factor);  \
        poly_offset[55] ^= _gf2ext128_mul_sse(poly_offset[311], mult_factor);  \
        poly_offset[56] ^= _gf2ext128_mul_sse(poly_offset[312], mult_factor);  \
        poly_offset[57] ^= _gf2ext128_mul_sse(poly_offset[313], mult_factor);  \
        poly_offset[58] ^= _gf2ext128_mul_sse(poly_offset[314], mult_factor);  \
        poly_offset[59] ^= _gf2ext128_mul_sse(poly_offset[315], mult_factor);  \
        poly_offset[60] ^= _gf2ext128_mul_sse(poly_offset[316], mult_factor);  \
        poly_offset[61] ^= _gf2ext128_mul_sse(poly_offset[317], mult_factor);  \
        poly_offset[62] ^= _gf2ext128_mul_sse(poly_offset[318], mult_factor);  \
        poly_offset[63] ^= _gf2ext128_mul_sse(poly_offset[319], mult_factor);  \
        poly_offset[64] ^= _gf2ext128_mul_sse(poly_offset[320], mult_factor);  \
        poly_offset[65] ^= _gf2ext128_mul_sse(poly_offset[321], mult_factor);  \
        poly_offset[66] ^= _gf2ext128_mul_sse(poly_offset[322], mult_factor);  \
        poly_offset[67] ^= _gf2ext128_mul_sse(poly_offset[323], mult_factor);  \
        poly_offset[68] ^= _gf2ext128_mul_sse(poly_offset[324], mult_factor);  \
        poly_offset[69] ^= _gf2ext128_mul_sse(poly_offset[325], mult_factor);  \
        poly_offset[70] ^= _gf2ext128_mul_sse(poly_offset[326], mult_factor);  \
        poly_offset[71] ^= _gf2ext128_mul_sse(poly_offset[327], mult_factor);  \
        poly_offset[72] ^= _gf2ext128_mul_sse(poly_offset[328], mult_factor);  \
        poly_offset[73] ^= _gf2ext128_mul_sse(poly_offset[329], mult_factor);  \
        poly_offset[74] ^= _gf2ext128_mul_sse(poly_offset[330], mult_factor);  \
        poly_offset[75] ^= _gf2ext128_mul_sse(poly_offset[331], mult_factor);  \
        poly_offset[76] ^= _gf2ext128_mul_sse(poly_offset[332], mult_factor);  \
        poly_offset[77] ^= _gf2ext128_mul_sse(poly_offset[333], mult_factor);  \
        poly_offset[78] ^= _gf2ext128_mul_sse(poly_offset[334], mult_factor);  \
        poly_offset[79] ^= _gf2ext128_mul_sse(poly_offset[335], mult_factor);  \
        poly_offset[80] ^= _gf2ext128_mul_sse(poly_offset[336], mult_factor);  \
        poly_offset[81] ^= _gf2ext128_mul_sse(poly_offset[337], mult_factor);  \
        poly_offset[82] ^= _gf2ext128_mul_sse(poly_offset[338], mult_factor);  \
        poly_offset[83] ^= _gf2ext128_mul_sse(poly_offset[339], mult_factor);  \
        poly_offset[84] ^= _gf2ext128_mul_sse(poly_offset[340], mult_factor);  \
        poly_offset[85] ^= _gf2ext128_mul_sse(poly_offset[341], mult_factor);  \
        poly_offset[86] ^= _gf2ext128_mul_sse(poly_offset[342], mult_factor);  \
        poly_offset[87] ^= _gf2ext128_mul_sse(poly_offset[343], mult_factor);  \
        poly_offset[88] ^= _gf2ext128_mul_sse(poly_offset[344], mult_factor);  \
        poly_offset[89] ^= _gf2ext128_mul_sse(poly_offset[345], mult_factor);  \
        poly_offset[90] ^= _gf2ext128_mul_sse(poly_offset[346], mult_factor);  \
        poly_offset[91] ^= _gf2ext128_mul_sse(poly_offset[347], mult_factor);  \
        poly_offset[92] ^= _gf2ext128_mul_sse(poly_offset[348], mult_factor);  \
        poly_offset[93] ^= _gf2ext128_mul_sse(poly_offset[349], mult_factor);  \
        poly_offset[94] ^= _gf2ext128_mul_sse(poly_offset[350], mult_factor);  \
        poly_offset[95] ^= _gf2ext128_mul_sse(poly_offset[351], mult_factor);  \
        poly_offset[96] ^= _gf2ext128_mul_sse(poly_offset[352], mult_factor);  \
        poly_offset[97] ^= _gf2ext128_mul_sse(poly_offset[353], mult_factor);  \
        poly_offset[98] ^= _gf2ext128_mul_sse(poly_offset[354], mult_factor);  \
        poly_offset[99] ^= _gf2ext128_mul_sse(poly_offset[355], mult_factor);  \
        poly_offset[100] ^= _gf2ext128_mul_sse(poly_offset[356], mult_factor);  \
        poly_offset[101] ^= _gf2ext128_mul_sse(poly_offset[357], mult_factor);  \
        poly_offset[102] ^= _gf2ext128_mul_sse(poly_offset[358], mult_factor);  \
        poly_offset[103] ^= _gf2ext128_mul_sse(poly_offset[359], mult_factor);  \
        poly_offset[104] ^= _gf2ext128_mul_sse(poly_offset[360], mult_factor);  \
        poly_offset[105] ^= _gf2ext128_mul_sse(poly_offset[361], mult_factor);  \
        poly_offset[106] ^= _gf2ext128_mul_sse(poly_offset[362], mult_factor);  \
        poly_offset[107] ^= _gf2ext128_mul_sse(poly_offset[363], mult_factor);  \
        poly_offset[108] ^= _gf2ext128_mul_sse(poly_offset[364], mult_factor);  \
        poly_offset[109] ^= _gf2ext128_mul_sse(poly_offset[365], mult_factor);  \
        poly_offset[110] ^= _gf2ext128_mul_sse(poly_offset[366], mult_factor);  \
        poly_offset[111] ^= _gf2ext128_mul_sse(poly_offset[367], mult_factor);  \
        poly_offset[112] ^= _gf2ext128_mul_sse(poly_offset[368], mult_factor);  \
        poly_offset[113] ^= _gf2ext128_mul_sse(poly_offset[369], mult_factor);  \
        poly_offset[114] ^= _gf2ext128_mul_sse(poly_offset[370], mult_factor);  \
        poly_offset[115] ^= _gf2ext128_mul_sse(poly_offset[371], mult_factor);  \
        poly_offset[116] ^= _gf2ext128_mul_sse(poly_offset[372], mult_factor);  \
        poly_offset[117] ^= _gf2ext128_mul_sse(poly_offset[373], mult_factor);  \
        poly_offset[118] ^= _gf2ext128_mul_sse(poly_offset[374], mult_factor);  \
        poly_offset[119] ^= _gf2ext128_mul_sse(poly_offset[375], mult_factor);  \
        poly_offset[120] ^= _gf2ext128_mul_sse(poly_offset[376], mult_factor);  \
        poly_offset[121] ^= _gf2ext128_mul_sse(poly_offset[377], mult_factor);  \
        poly_offset[122] ^= _gf2ext128_mul_sse(poly_offset[378], mult_factor);  \
        poly_offset[123] ^= _gf2ext128_mul_sse(poly_offset[379], mult_factor);  \
        poly_offset[124] ^= _gf2ext128_mul_sse(poly_offset[380], mult_factor);  \
        poly_offset[125] ^= _gf2ext128_mul_sse(poly_offset[381], mult_factor);  \
        poly_offset[126] ^= _gf2ext128_mul_sse(poly_offset[382], mult_factor);  \
        poly_offset[127] ^= _gf2ext128_mul_sse(poly_offset[383], mult_factor);  \
        poly_offset[128] ^= _gf2ext128_mul_sse(poly_offset[384], mult_factor);  \
        poly_offset[129] ^= _gf2ext128_mul_sse(poly_offset[385], mult_factor);  \
        poly_offset[130] ^= _gf2ext128_mul_sse(poly_offset[386], mult_factor);  \
        poly_offset[131] ^= _gf2ext128_mul_sse(poly_offset[387], mult_factor);  \
        poly_offset[132] ^= _gf2ext128_mul_sse(poly_offset[388], mult_factor);  \
        poly_offset[133] ^= _gf2ext128_mul_sse(poly_offset[389], mult_factor);  \
        poly_offset[134] ^= _gf2ext128_mul_sse(poly_offset[390], mult_factor);  \
        poly_offset[135] ^= _gf2ext128_mul_sse(poly_offset[391], mult_factor);  \
        poly_offset[136] ^= _gf2ext128_mul_sse(poly_offset[392], mult_factor);  \
        poly_offset[137] ^= _gf2ext128_mul_sse(poly_offset[393], mult_factor);  \
        poly_offset[138] ^= _gf2ext128_mul_sse(poly_offset[394], mult_factor);  \
        poly_offset[139] ^= _gf2ext128_mul_sse(poly_offset[395], mult_factor);  \
        poly_offset[140] ^= _gf2ext128_mul_sse(poly_offset[396], mult_factor);  \
        poly_offset[141] ^= _gf2ext128_mul_sse(poly_offset[397], mult_factor);  \
        poly_offset[142] ^= _gf2ext128_mul_sse(poly_offset[398], mult_factor);  \
        poly_offset[143] ^= _gf2ext128_mul_sse(poly_offset[399], mult_factor);  \
        poly_offset[144] ^= _gf2ext128_mul_sse(poly_offset[400], mult_factor);  \
        poly_offset[145] ^= _gf2ext128_mul_sse(poly_offset[401], mult_factor);  \
        poly_offset[146] ^= _gf2ext128_mul_sse(poly_offset[402], mult_factor);  \
        poly_offset[147] ^= _gf2ext128_mul_sse(poly_offset[403], mult_factor);  \
        poly_offset[148] ^= _gf2ext128_mul_sse(poly_offset[404], mult_factor);  \
        poly_offset[149] ^= _gf2ext128_mul_sse(poly_offset[405], mult_factor);  \
        poly_offset[150] ^= _gf2ext128_mul_sse(poly_offset[406], mult_factor);  \
        poly_offset[151] ^= _gf2ext128_mul_sse(poly_offset[407], mult_factor);  \
        poly_offset[152] ^= _gf2ext128_mul_sse(poly_offset[408], mult_factor);  \
        poly_offset[153] ^= _gf2ext128_mul_sse(poly_offset[409], mult_factor);  \
        poly_offset[154] ^= _gf2ext128_mul_sse(poly_offset[410], mult_factor);  \
        poly_offset[155] ^= _gf2ext128_mul_sse(poly_offset[411], mult_factor);  \
        poly_offset[156] ^= _gf2ext128_mul_sse(poly_offset[412], mult_factor);  \
        poly_offset[157] ^= _gf2ext128_mul_sse(poly_offset[413], mult_factor);  \
        poly_offset[158] ^= _gf2ext128_mul_sse(poly_offset[414], mult_factor);  \
        poly_offset[159] ^= _gf2ext128_mul_sse(poly_offset[415], mult_factor);  \
        poly_offset[160] ^= _gf2ext128_mul_sse(poly_offset[416], mult_factor);  \
        poly_offset[161] ^= _gf2ext128_mul_sse(poly_offset[417], mult_factor);  \
        poly_offset[162] ^= _gf2ext128_mul_sse(poly_offset[418], mult_factor);  \
        poly_offset[163] ^= _gf2ext128_mul_sse(poly_offset[419], mult_factor);  \
        poly_offset[164] ^= _gf2ext128_mul_sse(poly_offset[420], mult_factor);  \
        poly_offset[165] ^= _gf2ext128_mul_sse(poly_offset[421], mult_factor);  \
        poly_offset[166] ^= _gf2ext128_mul_sse(poly_offset[422], mult_factor);  \
        poly_offset[167] ^= _gf2ext128_mul_sse(poly_offset[423], mult_factor);  \
        poly_offset[168] ^= _gf2ext128_mul_sse(poly_offset[424], mult_factor);  \
        poly_offset[169] ^= _gf2ext128_mul_sse(poly_offset[425], mult_factor);  \
        poly_offset[170] ^= _gf2ext128_mul_sse(poly_offset[426], mult_factor);  \
        poly_offset[171] ^= _gf2ext128_mul_sse(poly_offset[427], mult_factor);  \
        poly_offset[172] ^= _gf2ext128_mul_sse(poly_offset[428], mult_factor);  \
        poly_offset[173] ^= _gf2ext128_mul_sse(poly_offset[429], mult_factor);  \
        poly_offset[174] ^= _gf2ext128_mul_sse(poly_offset[430], mult_factor);  \
        poly_offset[175] ^= _gf2ext128_mul_sse(poly_offset[431], mult_factor);  \
        poly_offset[176] ^= _gf2ext128_mul_sse(poly_offset[432], mult_factor);  \
        poly_offset[177] ^= _gf2ext128_mul_sse(poly_offset[433], mult_factor);  \
        poly_offset[178] ^= _gf2ext128_mul_sse(poly_offset[434], mult_factor);  \
        poly_offset[179] ^= _gf2ext128_mul_sse(poly_offset[435], mult_factor);  \
        poly_offset[180] ^= _gf2ext128_mul_sse(poly_offset[436], mult_factor);  \
        poly_offset[181] ^= _gf2ext128_mul_sse(poly_offset[437], mult_factor);  \
        poly_offset[182] ^= _gf2ext128_mul_sse(poly_offset[438], mult_factor);  \
        poly_offset[183] ^= _gf2ext128_mul_sse(poly_offset[439], mult_factor);  \
        poly_offset[184] ^= _gf2ext128_mul_sse(poly_offset[440], mult_factor);  \
        poly_offset[185] ^= _gf2ext128_mul_sse(poly_offset[441], mult_factor);  \
        poly_offset[186] ^= _gf2ext128_mul_sse(poly_offset[442], mult_factor);  \
        poly_offset[187] ^= _gf2ext128_mul_sse(poly_offset[443], mult_factor);  \
        poly_offset[188] ^= _gf2ext128_mul_sse(poly_offset[444], mult_factor);  \
        poly_offset[189] ^= _gf2ext128_mul_sse(poly_offset[445], mult_factor);  \
        poly_offset[190] ^= _gf2ext128_mul_sse(poly_offset[446], mult_factor);  \
        poly_offset[191] ^= _gf2ext128_mul_sse(poly_offset[447], mult_factor);  \
        poly_offset[192] ^= _gf2ext128_mul_sse(poly_offset[448], mult_factor);  \
        poly_offset[193] ^= _gf2ext128_mul_sse(poly_offset[449], mult_factor);  \
        poly_offset[194] ^= _gf2ext128_mul_sse(poly_offset[450], mult_factor);  \
        poly_offset[195] ^= _gf2ext128_mul_sse(poly_offset[451], mult_factor);  \
        poly_offset[196] ^= _gf2ext128_mul_sse(poly_offset[452], mult_factor);  \
        poly_offset[197] ^= _gf2ext128_mul_sse(poly_offset[453], mult_factor);  \
        poly_offset[198] ^= _gf2ext128_mul_sse(poly_offset[454], mult_factor);  \
        poly_offset[199] ^= _gf2ext128_mul_sse(poly_offset[455], mult_factor);  \
        poly_offset[200] ^= _gf2ext128_mul_sse(poly_offset[456], mult_factor);  \
        poly_offset[201] ^= _gf2ext128_mul_sse(poly_offset[457], mult_factor);  \
        poly_offset[202] ^= _gf2ext128_mul_sse(poly_offset[458], mult_factor);  \
        poly_offset[203] ^= _gf2ext128_mul_sse(poly_offset[459], mult_factor);  \
        poly_offset[204] ^= _gf2ext128_mul_sse(poly_offset[460], mult_factor);  \
        poly_offset[205] ^= _gf2ext128_mul_sse(poly_offset[461], mult_factor);  \
        poly_offset[206] ^= _gf2ext128_mul_sse(poly_offset[462], mult_factor);  \
        poly_offset[207] ^= _gf2ext128_mul_sse(poly_offset[463], mult_factor);  \
        poly_offset[208] ^= _gf2ext128_mul_sse(poly_offset[464], mult_factor);  \
        poly_offset[209] ^= _gf2ext128_mul_sse(poly_offset[465], mult_factor);  \
        poly_offset[210] ^= _gf2ext128_mul_sse(poly_offset[466], mult_factor);  \
        poly_offset[211] ^= _gf2ext128_mul_sse(poly_offset[467], mult_factor);  \
        poly_offset[212] ^= _gf2ext128_mul_sse(poly_offset[468], mult_factor);  \
        poly_offset[213] ^= _gf2ext128_mul_sse(poly_offset[469], mult_factor);  \
        poly_offset[214] ^= _gf2ext128_mul_sse(poly_offset[470], mult_factor);  \
        poly_offset[215] ^= _gf2ext128_mul_sse(poly_offset[471], mult_factor);  \
        poly_offset[216] ^= _gf2ext128_mul_sse(poly_offset[472], mult_factor);  \
        poly_offset[217] ^= _gf2ext128_mul_sse(poly_offset[473], mult_factor);  \
        poly_offset[218] ^= _gf2ext128_mul_sse(poly_offset[474], mult_factor);  \
        poly_offset[219] ^= _gf2ext128_mul_sse(poly_offset[475], mult_factor);  \
        poly_offset[220] ^= _gf2ext128_mul_sse(poly_offset[476], mult_factor);  \
        poly_offset[221] ^= _gf2ext128_mul_sse(poly_offset[477], mult_factor);  \
        poly_offset[222] ^= _gf2ext128_mul_sse(poly_offset[478], mult_factor);  \
        poly_offset[223] ^= _gf2ext128_mul_sse(poly_offset[479], mult_factor);  \
        poly_offset[224] ^= _gf2ext128_mul_sse(poly_offset[480], mult_factor);  \
        poly_offset[225] ^= _gf2ext128_mul_sse(poly_offset[481], mult_factor);  \
        poly_offset[226] ^= _gf2ext128_mul_sse(poly_offset[482], mult_factor);  \
        poly_offset[227] ^= _gf2ext128_mul_sse(poly_offset[483], mult_factor);  \
        poly_offset[228] ^= _gf2ext128_mul_sse(poly_offset[484], mult_factor);  \
        poly_offset[229] ^= _gf2ext128_mul_sse(poly_offset[485], mult_factor);  \
        poly_offset[230] ^= _gf2ext128_mul_sse(poly_offset[486], mult_factor);  \
        poly_offset[231] ^= _gf2ext128_mul_sse(poly_offset[487], mult_factor);  \
        poly_offset[232] ^= _gf2ext128_mul_sse(poly_offset[488], mult_factor);  \
        poly_offset[233] ^= _gf2ext128_mul_sse(poly_offset[489], mult_factor);  \
        poly_offset[234] ^= _gf2ext128_mul_sse(poly_offset[490], mult_factor);  \
        poly_offset[235] ^= _gf2ext128_mul_sse(poly_offset[491], mult_factor);  \
        poly_offset[236] ^= _gf2ext128_mul_sse(poly_offset[492], mult_factor);  \
        poly_offset[237] ^= _gf2ext128_mul_sse(poly_offset[493], mult_factor);  \
        poly_offset[238] ^= _gf2ext128_mul_sse(poly_offset[494], mult_factor);  \
        poly_offset[239] ^= _gf2ext128_mul_sse(poly_offset[495], mult_factor);  \
        poly_offset[240] ^= _gf2ext128_mul_sse(poly_offset[496], mult_factor);  \
        poly_offset[241] ^= _gf2ext128_mul_sse(poly_offset[497], mult_factor);  \
        poly_offset[242] ^= _gf2ext128_mul_sse(poly_offset[498], mult_factor);  \
        poly_offset[243] ^= _gf2ext128_mul_sse(poly_offset[499], mult_factor);  \
        poly_offset[244] ^= _gf2ext128_mul_sse(poly_offset[500], mult_factor);  \
        poly_offset[245] ^= _gf2ext128_mul_sse(poly_offset[501], mult_factor);  \
        poly_offset[246] ^= _gf2ext128_mul_sse(poly_offset[502], mult_factor);  \
        poly_offset[247] ^= _gf2ext128_mul_sse(poly_offset[503], mult_factor);  \
        poly_offset[248] ^= _gf2ext128_mul_sse(poly_offset[504], mult_factor);  \
        poly_offset[249] ^= _gf2ext128_mul_sse(poly_offset[505], mult_factor);  \
        poly_offset[250] ^= _gf2ext128_mul_sse(poly_offset[506], mult_factor);  \
        poly_offset[251] ^= _gf2ext128_mul_sse(poly_offset[507], mult_factor);  \
        poly_offset[252] ^= _gf2ext128_mul_sse(poly_offset[508], mult_factor);  \
        poly_offset[253] ^= _gf2ext128_mul_sse(poly_offset[509], mult_factor);  \
        poly_offset[254] ^= _gf2ext128_mul_sse(poly_offset[510], mult_factor);  \
        poly_offset[255] ^= _gf2ext128_mul_sse(poly_offset[511], mult_factor);  \
        poly_offset[256] ^= poly_offset[0];                             \
        poly_offset[257] ^= poly_offset[1];                             \
        poly_offset[258] ^= poly_offset[2];                             \
        poly_offset[259] ^= poly_offset[3];                             \
        poly_offset[260] ^= poly_offset[4];                             \
        poly_offset[261] ^= poly_offset[5];                             \
        poly_offset[262] ^= poly_offset[6];                             \
        poly_offset[263] ^= poly_offset[7];                             \
        poly_offset[264] ^= poly_offset[8];                             \
        poly_offset[265] ^= poly_offset[9];                             \
        poly_offset[266] ^= poly_offset[10];                             \
        poly_offset[267] ^= poly_offset[11];                             \
        poly_offset[268] ^= poly_offset[12];                             \
        poly_offset[269] ^= poly_offset[13];                             \
        poly_offset[270] ^= poly_offset[14];                             \
        poly_offset[271] ^= poly_offset[15];                             \
        poly_offset[272] ^= poly_offset[16];                             \
        poly_offset[273] ^= poly_offset[17];                             \
        poly_offset[274] ^= poly_offset[18];                             \
        poly_offset[275] ^= poly_offset[19];                             \
        poly_offset[276] ^= poly_offset[20];                             \
        poly_offset[277] ^= poly_offset[21];                             \
        poly_offset[278] ^= poly_offset[22];                             \
        poly_offset[279] ^= poly_offset[23];                             \
        poly_offset[280] ^= poly_offset[24];                             \
        poly_offset[281] ^= poly_offset[25];                             \
        poly_offset[282] ^= poly_offset[26];                             \
        poly_offset[283] ^= poly_offset[27];                             \
        poly_offset[284] ^= poly_offset[28];                             \
        poly_offset[285] ^= poly_offset[29];                             \
        poly_offset[286] ^= poly_offset[30];                             \
        poly_offset[287] ^= poly_offset[31];                             \
        poly_offset[288] ^= poly_offset[32];                             \
        poly_offset[289] ^= poly_offset[33];                             \
        poly_offset[290] ^= poly_offset[34];                             \
        poly_offset[291] ^= poly_offset[35];                             \
        poly_offset[292] ^= poly_offset[36];                             \
        poly_offset[293] ^= poly_offset[37];                             \
        poly_offset[294] ^= poly_offset[38];                             \
        poly_offset[295] ^= poly_offset[39];                             \
        poly_offset[296] ^= poly_offset[40];                             \
        poly_offset[297] ^= poly_offset[41];                             \
        poly_offset[298] ^= poly_offset[42];                             \
        poly_offset[299] ^= poly_offset[43];                             \
        poly_offset[300] ^= poly_offset[44];                             \
        poly_offset[301] ^= poly_offset[45];                             \
        poly_offset[302] ^= poly_offset[46];                             \
        poly_offset[303] ^= poly_offset[47];                             \
        poly_offset[304] ^= poly_offset[48];                             \
        poly_offset[305] ^= poly_offset[49];                             \
        poly_offset[306] ^= poly_offset[50];                             \
        poly_offset[307] ^= poly_offset[51];                             \
        poly_offset[308] ^= poly_offset[52];                             \
        poly_offset[309] ^= poly_offset[53];                             \
        poly_offset[310] ^= poly_offset[54];                             \
        poly_offset[311] ^= poly_offset[55];                             \
        poly_offset[312] ^= poly_offset[56];                             \
        poly_offset[313] ^= poly_offset[57];                             \
        poly_offset[314] ^= poly_offset[58];                             \
        poly_offset[315] ^= poly_offset[59];                             \
        poly_offset[316] ^= poly_offset[60];                             \
        poly_offset[317] ^= poly_offset[61];                             \
        poly_offset[318] ^= poly_offset[62];                             \
        poly_offset[319] ^= poly_offset[63];                             \
        poly_offset[320] ^= poly_offset[64];                             \
        poly_offset[321] ^= poly_offset[65];                             \
        poly_offset[322] ^= poly_offset[66];                             \
        poly_offset[323] ^= poly_offset[67];                             \
        poly_offset[324] ^= poly_offset[68];                             \
        poly_offset[325] ^= poly_offset[69];                             \
        poly_offset[326] ^= poly_offset[70];                             \
        poly_offset[327] ^= poly_offset[71];                             \
        poly_offset[328] ^= poly_offset[72];                             \
        poly_offset[329] ^= poly_offset[73];                             \
        poly_offset[330] ^= poly_offset[74];                             \
        poly_offset[331] ^= poly_offset[75];                             \
        poly_offset[332] ^= poly_offset[76];                             \
        poly_offset[333] ^= poly_offset[77];                             \
        poly_offset[334] ^= poly_offset[78];                             \
        poly_offset[335] ^= poly_offset[79];                             \
        poly_offset[336] ^= poly_offset[80];                             \
        poly_offset[337] ^= poly_offset[81];                             \
        poly_offset[338] ^= poly_offset[82];                             \
        poly_offset[339] ^= poly_offset[83];                             \
        poly_offset[340] ^= poly_offset[84];                             \
        poly_offset[341] ^= poly_offset[85];                             \
        poly_offset[342] ^= poly_offset[86];                             \
        poly_offset[343] ^= poly_offset[87];                             \
        poly_offset[344] ^= poly_offset[88];                             \
        poly_offset[345] ^= poly_offset[89];                             \
        poly_offset[346] ^= poly_offset[90];                             \
        poly_offset[347] ^= poly_offset[91];                             \
        poly_offset[348] ^= poly_offset[92];                             \
        poly_offset[349] ^= poly_offset[93];                             \
        poly_offset[350] ^= poly_offset[94];                             \
        poly_offset[351] ^= poly_offset[95];                             \
        poly_offset[352] ^= poly_offset[96];                             \
        poly_offset[353] ^= poly_offset[97];                             \
        poly_offset[354] ^= poly_offset[98];                             \
        poly_offset[355] ^= poly_offset[99];                             \
        poly_offset[356] ^= poly_offset[100];                             \
        poly_offset[357] ^= poly_offset[101];                             \
        poly_offset[358] ^= poly_offset[102];                             \
        poly_offset[359] ^= poly_offset[103];                             \
        poly_offset[360] ^= poly_offset[104];                             \
        poly_offset[361] ^= poly_offset[105];                             \
        poly_offset[362] ^= poly_offset[106];                             \
        poly_offset[363] ^= poly_offset[107];                             \
        poly_offset[364] ^= poly_offset[108];                             \
        poly_offset[365] ^= poly_offset[109];                             \
        poly_offset[366] ^= poly_offset[110];                             \
        poly_offset[367] ^= poly_offset[111];                             \
        poly_offset[368] ^= poly_offset[112];                             \
        poly_offset[369] ^= poly_offset[113];                             \
        poly_offset[370] ^= poly_offset[114];                             \
        poly_offset[371] ^= poly_offset[115];                             \
        poly_offset[372] ^= poly_offset[116];                             \
        poly_offset[373] ^= poly_offset[117];                             \
        poly_offset[374] ^= poly_offset[118];                             \
        poly_offset[375] ^= poly_offset[119];                             \
        poly_offset[376] ^= poly_offset[120];                             \
        poly_offset[377] ^= poly_offset[121];                             \
        poly_offset[378] ^= poly_offset[122];                             \
        poly_offset[379] ^= poly_offset[123];                             \
        poly_offset[380] ^= poly_offset[124];                             \
        poly_offset[381] ^= poly_offset[125];                             \
        poly_offset[382] ^= poly_offset[126];                             \
        poly_offset[383] ^= poly_offset[127];                             \
        poly_offset[384] ^= poly_offset[128];                             \
        poly_offset[385] ^= poly_offset[129];                             \
        poly_offset[386] ^= poly_offset[130];                             \
        poly_offset[387] ^= poly_offset[131];                             \
        poly_offset[388] ^= poly_offset[132];                             \
        poly_offset[389] ^= poly_offset[133];                             \
        poly_offset[390] ^= poly_offset[134];                             \
        poly_offset[391] ^= poly_offset[135];                             \
        poly_offset[392] ^= poly_offset[136];                             \
        poly_offset[393] ^= poly_offset[137];                             \
        poly_offset[394] ^= poly_offset[138];                             \
        poly_offset[395] ^= poly_offset[139];                             \
        poly_offset[396] ^= poly_offset[140];                             \
        poly_offset[397] ^= poly_offset[141];                             \
        poly_offset[398] ^= poly_offset[142];                             \
        poly_offset[399] ^= poly_offset[143];                             \
        poly_offset[400] ^= poly_offset[144];                             \
        poly_offset[401] ^= poly_offset[145];                             \
        poly_offset[402] ^= poly_offset[146];                             \
        poly_offset[403] ^= poly_offset[147];                             \
        poly_offset[404] ^= poly_offset[148];                             \
        poly_offset[405] ^= poly_offset[149];                             \
        poly_offset[406] ^= poly_offset[150];                             \
        poly_offset[407] ^= poly_offset[151];                             \
        poly_offset[408] ^= poly_offset[152];                             \
        poly_offset[409] ^= poly_offset[153];                             \
        poly_offset[410] ^= poly_offset[154];                             \
        poly_offset[411] ^= poly_offset[155];                             \
        poly_offset[412] ^= poly_offset[156];                             \
        poly_offset[413] ^= poly_offset[157];                             \
        poly_offset[414] ^= poly_offset[158];                             \
        poly_offset[415] ^= poly_offset[159];                             \
        poly_offset[416] ^= poly_offset[160];                             \
        poly_offset[417] ^= poly_offset[161];                             \
        poly_offset[418] ^= poly_offset[162];                             \
        poly_offset[419] ^= poly_offset[163];                             \
        poly_offset[420] ^= poly_offset[164];                             \
        poly_offset[421] ^= poly_offset[165];                             \
        poly_offset[422] ^= poly_offset[166];                             \
        poly_offset[423] ^= poly_offset[167];                             \
        poly_offset[424] ^= poly_offset[168];                             \
        poly_offset[425] ^= poly_offset[169];                             \
        poly_offset[426] ^= poly_offset[170];                             \
        poly_offset[427] ^= poly_offset[171];                             \
        poly_offset[428] ^= poly_offset[172];                             \
        poly_offset[429] ^= poly_offset[173];                             \
        poly_offset[430] ^= poly_offset[174];                             \
        poly_offset[431] ^= poly_offset[175];                             \
        poly_offset[432] ^= poly_offset[176];                             \
        poly_offset[433] ^= poly_offset[177];                             \
        poly_offset[434] ^= poly_offset[178];                             \
        poly_offset[435] ^= poly_offset[179];                             \
        poly_offset[436] ^= poly_offset[180];                             \
        poly_offset[437] ^= poly_offset[181];                             \
        poly_offset[438] ^= poly_offset[182];                             \
        poly_offset[439] ^= poly_offset[183];                             \
        poly_offset[440] ^= poly_offset[184];                             \
        poly_offset[441] ^= poly_offset[185];                             \
        poly_offset[442] ^= poly_offset[186];                             \
        poly_offset[443] ^= poly_offset[187];                             \
        poly_offset[444] ^= poly_offset[188];                             \
        poly_offset[445] ^= poly_offset[189];                             \
        poly_offset[446] ^= poly_offset[190];                             \
        poly_offset[447] ^= poly_offset[191];                             \
        poly_offset[448] ^= poly_offset[192];                             \
        poly_offset[449] ^= poly_offset[193];                             \
        poly_offset[450] ^= poly_offset[194];                             \
        poly_offset[451] ^= poly_offset[195];                             \
        poly_offset[452] ^= poly_offset[196];                             \
        poly_offset[453] ^= poly_offset[197];                             \
        poly_offset[454] ^= poly_offset[198];                             \
        poly_offset[455] ^= poly_offset[199];                             \
        poly_offset[456] ^= poly_offset[200];                             \
        poly_offset[457] ^= poly_offset[201];                             \
        poly_offset[458] ^= poly_offset[202];                             \
        poly_offset[459] ^= poly_offset[203];                             \
        poly_offset[460] ^= poly_offset[204];                             \
        poly_offset[461] ^= poly_offset[205];                             \
        poly_offset[462] ^= poly_offset[206];                             \
        poly_offset[463] ^= poly_offset[207];                             \
        poly_offset[464] ^= poly_offset[208];                             \
        poly_offset[465] ^= poly_offset[209];                             \
        poly_offset[466] ^= poly_offset[210];                             \
        poly_offset[467] ^= poly_offset[211];                             \
        poly_offset[468] ^= poly_offset[212];                             \
        poly_offset[469] ^= poly_offset[213];                             \
        poly_offset[470] ^= poly_offset[214];                             \
        poly_offset[471] ^= poly_offset[215];                             \
        poly_offset[472] ^= poly_offset[216];                             \
        poly_offset[473] ^= poly_offset[217];                             \
        poly_offset[474] ^= poly_offset[218];                             \
        poly_offset[475] ^= poly_offset[219];                             \
        poly_offset[476] ^= poly_offset[220];                             \
        poly_offset[477] ^= poly_offset[221];                             \
        poly_offset[478] ^= poly_offset[222];                             \
        poly_offset[479] ^= poly_offset[223];                             \
        poly_offset[480] ^= poly_offset[224];                             \
        poly_offset[481] ^= poly_offset[225];                             \
        poly_offset[482] ^= poly_offset[226];                             \
        poly_offset[483] ^= poly_offset[227];                             \
        poly_offset[484] ^= poly_offset[228];                             \
        poly_offset[485] ^= poly_offset[229];                             \
        poly_offset[486] ^= poly_offset[230];                             \
        poly_offset[487] ^= poly_offset[231];                             \
        poly_offset[488] ^= poly_offset[232];                             \
        poly_offset[489] ^= poly_offset[233];                             \
        poly_offset[490] ^= poly_offset[234];                             \
        poly_offset[491] ^= poly_offset[235];                             \
        poly_offset[492] ^= poly_offset[236];                             \
        poly_offset[493] ^= poly_offset[237];                             \
        poly_offset[494] ^= poly_offset[238];                             \
        poly_offset[495] ^= poly_offset[239];                             \
        poly_offset[496] ^= poly_offset[240];                             \
        poly_offset[497] ^= poly_offset[241];                             \
        poly_offset[498] ^= poly_offset[242];                             \
        poly_offset[499] ^= poly_offset[243];                             \
        poly_offset[500] ^= poly_offset[244];                             \
        poly_offset[501] ^= poly_offset[245];                             \
        poly_offset[502] ^= poly_offset[246];                             \
        poly_offset[503] ^= poly_offset[247];                             \
        poly_offset[504] ^= poly_offset[248];                             \
        poly_offset[505] ^= poly_offset[249];                             \
        poly_offset[506] ^= poly_offset[250];                             \
        poly_offset[507] ^= poly_offset[251];                             \
        poly_offset[508] ^= poly_offset[252];                             \
        poly_offset[509] ^= poly_offset[253];                             \
        poly_offset[510] ^= poly_offset[254];                             \
        poly_offset[511] ^= poly_offset[255];                             \
    } while (0)
    



#endif
